// existing code...

const bountyUrl = await resolveBountyUrl();
if (bountyUrl) {
  // existing code...
}

// existing code...

async function resolveBountyUrl() {
  // existing code...
}

// existing code...