// AUTO-GENERATED by scripts/build-chat-context.ts — do not edit manually.
// Regenerate with: npx tsx scripts/build-chat-context.ts

export const STYX_KNOWLEDGE = `=== BEHAVIORAL LOGIC (oath categories, constants, streams) ===
File: src/shared/libs/behavioral-logic.ts

/**
 * Behavioral Logic: The Kernel of Oaths & Physics
 * 
 * This file defines the exhaustive taxonomy of behaviors tracked by Styx.
 */

export enum OathCategory {
  // 1. Biological Stream (Hardware Oracle)
  WEIGHT_MANAGEMENT = "BIOLOGICAL_WEIGHT",
  CARDIOVASCULAR_STAMINA = "BIOLOGICAL_CARDIO",
  GLUCOSE_STABILITY = "BIOLOGICAL_METABOLIC",
  SLEEP_INTEGRITY = "BIOLOGICAL_SLEEP",
  SOBRIETY_HRV = "BIOLOGICAL_SOBRIETY",

  // 2. Cognitive Stream (Device Oracle)
  DIGITAL_FASTING = "COGNITIVE_DIGITAL",
  DEEP_WORK_FOCUS = "COGNITIVE_FOCUS",
  INBOX_ZERO = "COGNITIVE_QUEUE",
  LEARNING_RETENTION = "COGNITIVE_LEARNING",

  // 3. Professional Stream (API Oracle)
  SALES_VELOCITY = "PROFESSIONAL_SALES",
  DEVELOPER_THROUGHPUT = "PROFESSIONAL_CODE",
  PUNCTUALITY = "PROFESSIONAL_TIME",

  // 4. Creative Stream (The Muse) - Proof of Process
  DEEP_WRITING = "CREATIVE_WRITING",
  VISUAL_ARTS = "CREATIVE_ART",
  MUSIC_PRACTICE = "CREATIVE_MUSIC",
  MAKER_BUILD = "CREATIVE_BUILD",

  // 5. Environmental Stream (Fury Audited)
  NUTRITIONAL_TRANSPARENCY = "VISUAL_NUTRITION",
  TIDINESS_MINIMALISM = "VISUAL_ENVIRONMENT",
  PERSONAL_PRESENTATION = "VISUAL_IMAGE",
  ACTIVE_READING = "VISUAL_LITERACY",

  // 6. Character Stream (Multi-Oracle)
  CIVIC_ENGAGEMENT = "SOCIAL_COMMUNITY",
  PHILANTHROPIC_VELOCITY = "SOCIAL_CHARITY",
  FAMILY_PRESENCE = "SOCIAL_CONNECTION",

  // 7. Recovery Stream (Abstinence Oracle)
  NO_CONTACT_BOUNDARY = "RECOVERY_NOCONTACT",
  SUBSTANCE_ABSTINENCE = "RECOVERY_SUBSTANCE",
  BEHAVIORAL_DETOX = "RECOVERY_DETOX",
  ENVIRONMENT_AVOIDANCE = "RECOVERY_AVOIDANCE",
}

export enum VerificationMethod {
  HARDWARE_HEALTHKIT = "HEALTHKIT",
  HARDWARE_HEALTHCONNECT = "HEALTHCONNECT",
  API_SCREEN_TIME = "SCREENTIME",
  API_THIRD_PARTY = "EXTERNAL_API",
  FURY_CONSENSUS = "FURY_NETWORK",
  TIME_LAPSE = "TIME_LAPSE_PROOF", // For Creative Stream
  GPS_GEOFENCE = "GPS",
  FINANCIAL_LEDGER = "LEDGER",
  DAILY_ATTESTATION = "ATTESTATION",
}

export const MAX_GRACE_DAYS_PER_MONTH = 2;
export const ONBOARDING_BONUS_AMOUNT = 500; // cents ($5.00)

/**
 * Theorem 2: Genesis Hash
 * Fixed 64-char hex value for the start of the tamper-evident log.
 */
export const GENESIS_HASH = '0000000000000000000000000000000000000000000000000000000000000000';

/**
 * Theorem 8: Isolation Guardrails
 * Maximum aggregate no-contact targets allowed across all active contracts.
 */
export const ABSOLUTE_MAX_ISOLATION_TARGETS = 10;

/**
 * AEGIS-04: Dispute Grace Period
 * Hours allowed to file a dispute before final stake liquidation.
 */
export const DISPUTE_GRACE_PERIOD_HOURS = 24;

/**
 * BE-01: Loss Aversion Anchor
 * Perceived pain of loss is ~2x pleasure of gain (λ = 1.955).
 * Reserved: Dynamic stake messaging (Phase Omega)
 */
export const LOSS_AVERSION_COEFFICIENT = 1.955;

/**
 * Theorem 7: Shadow-Ban Threshold
 * Integrity score below which a Fury is excluded from job rotation.
 */
export const SHADOW_BAN_THRESHOLD = 20;

/**
 * Theorem 7: Default Consensus Size
 * Standard number of Furies assigned to each proof audit.
 */
export const FURY_CONSENSUS_SIZE = 3;

/**
 * BE-05: Dynamic Downscaling Threshold
 */
export const DOWNSCALE_STRIKE_THRESHOLD = 3;

/**
 * CG-04: Cool-Off Period
 * Forced lockout days after a failure spree.
 */
export const FAILURE_COOL_OFF_DAYS = 7;

/**
 * AEGIS-01: Medical Guardrails
 */
export const MIN_SAFE_BMI = 18.5;
export const MAX_WEEKLY_LOSS_VELOCITY_PCT = 0.02;

/**
 * RECOVERY-01: Recovery Stream Guardrails
 * Forces re-evaluation cadence and prevents isolation patterns.
 */
export const MAX_NOCONTACT_DURATION_DAYS = 30;
export const MAX_NOCONTACT_TARGETS = 3;
export const NOCONTACT_MISS_STRIKE_THRESHOLD = 3;

/**
 * F-UX-09: Resilience Badge System
 * Psychological reframing of failure as a pivot point.
 */
export enum BadgeType {
  PHOENIX_RECOVERY = 'PHOENIX_RECOVERY', // Completed contract after a failure
  CONSISTENCY_KING = 'CONSISTENCY_KING', // 30-day streak
  FURY_MASTER = 'FURY_MASTER', // >200 audits with high accuracy
  EARLY_ADOPTER = 'EARLY_ADOPTER', // Beta participant
}

export interface Badge {
  type: BadgeType;
  grantedAt: Date;
  metadata?: Record<string, any>;
}

/**
 * Oracle mapping: which verification methods are allowed for each oath stream.
 * BIOLOGICAL requires hardware oracles; COGNITIVE uses device APIs; etc.
 */
const OATH_METHOD_MAP: Record<string, VerificationMethod[]> = {
  BIOLOGICAL: [VerificationMethod.HARDWARE_HEALTHKIT, VerificationMethod.HARDWARE_HEALTHCONNECT],
  COGNITIVE: [VerificationMethod.API_SCREEN_TIME, VerificationMethod.API_THIRD_PARTY],
  PROFESSIONAL: [VerificationMethod.API_THIRD_PARTY, VerificationMethod.FINANCIAL_LEDGER],
  CREATIVE: [VerificationMethod.TIME_LAPSE, VerificationMethod.FURY_CONSENSUS],
  VISUAL: [VerificationMethod.FURY_CONSENSUS, VerificationMethod.GPS_GEOFENCE],
  SOCIAL: [VerificationMethod.FURY_CONSENSUS, VerificationMethod.GPS_GEOFENCE],
  RECOVERY: [VerificationMethod.DAILY_ATTESTATION, VerificationMethod.API_SCREEN_TIME, VerificationMethod.FURY_CONSENSUS],
};

/**
 * Validates that an oath category uses a correct oracle/verification method.
 * Returns true if the mapping is valid, false if the method is not allowed for the stream.
 */
export function validateOathMapping(category: OathCategory, method: VerificationMethod): boolean {
  const categoryValue = category as string;
  // Extract the stream prefix (e.g., "BIOLOGICAL" from "BIOLOGICAL_WEIGHT")
  const stream = categoryValue.split('_')[0];
  const allowedMethods = OATH_METHOD_MAP[stream];

  if (!allowedMethods) return false;
  return allowedMethods.includes(method);
}

export interface GraceDayResult {
  success: boolean;
  reason?: string;
  newDeadline?: Date;
}

/**
 * Uses one grace day for a contract — extends the deadline by 24 hours.
 * Caller must pass the current grace_days_used count and the current ends_at.
 * Returns the new deadline if successful, or a rejection reason.
 */
export function useGraceDay(
  graceDaysUsedThisMonth: number,
  currentEndsAt: Date,
): GraceDayResult {
  if (graceDaysUsedThisMonth >= MAX_GRACE_DAYS_PER_MONTH) {
    return { success: false, reason: \`Maximum \${MAX_GRACE_DAYS_PER_MONTH} grace days per month exceeded\` };
  }
  const newDeadline = new Date(currentEndsAt.getTime() + 24 * 60 * 60 * 1000);
  return { success: true, newDeadline };
}

export interface OnboardingBonusResult {
  granted: boolean;
  amount: number;
  reason?: string;
}

/**
 * Determines if a user qualifies for the onboarding bonus ($5 credit on first contract).
 * Caller must pass the user's total contract count.
 */
export function grantOnboardingBonus(totalContracts: number): OnboardingBonusResult {
  if (totalContracts > 0) {
    return { granted: false, amount: 0, reason: 'User already has prior contracts' };
  }
  return { granted: true, amount: ONBOARDING_BONUS_AMOUNT };
}

/**
 * DEPRECATED: Goal ethics screening has been moved to
 * src/api/services/intelligence/goal-ethics.service.ts
 * to fix the shared → api dependency inversion.
 * Import GoalEthicsService from the API layer instead.
 */

/** Active oath streams supported in MVP */
export const ACTIVE_OATH_STREAMS = [
  'BIOLOGICAL',
  'COGNITIVE',
  'PROFESSIONAL',
  'CREATIVE',
  'VISUAL',
  'SOCIAL',
  'RECOVERY',
] as const;

/** Check if an oath category is supported in the current MVP */
export function isOathStreamActive(category: OathCategory): boolean {
  const stream = (category as string).split('_')[0];
  return (ACTIVE_OATH_STREAMS as readonly string[]).includes(stream);
}

/**
 * RECOVERY-02: 90-Day Execution Matrix (Theorem 9)
 * Maps psychological vulnerability peaks to system state triggers.
 */
export enum RecoveryState {
  LOCKDOWN = 'STATE_LOCKDOWN',
  WEEKEND_SHIELD = 'STATE_WEEKEND_SHIELD',
  REWARD_INJECTION = 'STATE_REWARD_INJECTION',
  FRICTION_DELAY = 'STATE_FRICTION_DELAY',
  ALPHA_COMPLETE = 'STATE_ALPHA_COMPLETE',
  NORMAL = 'STATE_NORMAL',
}

export const RECOVERY_MATRIX = {
  [RecoveryState.LOCKDOWN]: {
    startDay: 0,
    endDay: 14,
    multiplier: 2.5,
    description: 'Acute Withdrawal (Panic Phase)',
  },
  [RecoveryState.WEEKEND_SHIELD]: {
    multiplier: 2.0,
    description: 'Structural Isolation (Weekend Void)',
  },
  [RecoveryState.REWARD_INJECTION]: {
    triggerDay: 21,
    refundPct: 0.05,
    description: 'Dopamine Trough (Anhedonia Pivot)',
  },
  [RecoveryState.FRICTION_DELAY]: {
    startDay: 45,
    endDay: 60,
    multiplier: 1.5,
    delayHrs: 48,
    description: 'Bargaining Stage',
  },
  [RecoveryState.ALPHA_COMPLETE]: {
    triggerDay: 90,
    feePct: 0,
    description: 'Identity Reconstruction (Omega Milestone)',
  },
};



=== INTEGRITY SCORE (algorithm, tiers, Fury accuracy) ===
File: src/shared/libs/integrity.ts

export const BASE_INTEGRITY = 50;
export const FRAUD_PENALTY = 15;
export const STRIKE_PENALTY = 20;
export const COMPLETION_BONUS = 5;
export const INTEGRITY_CEILING_HIGH = 500;
export const CEILING_PENALTY_RATE = 0.5;

export const AUDITOR_STAKE_AMOUNT = 200; // cents ($2.00)
export const AUDITOR_HARASSMENT_THRESHOLD = 3;

// Base Models
export interface UserHistory {
  userId: string;
  completedOaths: number;
  fraudStrikes: number;
  failedOaths: number;
  monthsInactive: number;
}

export interface FuryHistory {
  furyId: string;
  successfulAudits: number;
  falseAccusations: number;
  totalAudits: number;
}

/**
 * Calculates a user's Integrity Score (IS) based on behavioral physics.
 * Base (50) + (5 per completed challenge) - (15 per fraud) - (20 per strike) - (1 per inactive month).
 */
export function calculateIntegrity(history: UserHistory): number {
  const base = BASE_INTEGRITY;
  const bonus = history.completedOaths * COMPLETION_BONUS;
  const fraudCost = history.fraudStrikes * FRAUD_PENALTY;
  const strikeCost = history.failedOaths * STRIKE_PENALTY;
  const decay = history.monthsInactive * 1; // 1 point decay per month

  let score = base + bonus - fraudCost - strikeCost - decay;

  score = Math.max(0, score);

  // Percentage-based compression above the high ceiling — fraud/strike
  // penalties remain meaningful even for top-tier users because the
  // compressed score keeps them within a range where fixed-point
  // deductions still move the needle.
  if (score > INTEGRITY_CEILING_HIGH) {
    score = INTEGRITY_CEILING_HIGH + (score - INTEGRITY_CEILING_HIGH) * CEILING_PENALTY_RATE;
  }

  return Math.round(score);
}

/**
 * Determines what financial tiers a user can access based on their Integrity Score.
 */
export function getAllowedTiers(score: number): string[] {
  if (score < 20) return ['RESTRICTED_MODE']; // Essentially Shadowbanned
  if (score < 50) return ['TIER_1_MICRO_STAKES']; // Under $20
  if (score < 100) return ['TIER_1_MICRO_STAKES', 'TIER_2_STANDARD']; // Up to $100
  if (score < 500) return ['TIER_1_MICRO_STAKES', 'TIER_2_STANDARD', 'TIER_3_HIGH_ROLLER']; // Up to $1000
  return ['TIER_1_MICRO_STAKES', 'TIER_2_STANDARD', 'TIER_3_HIGH_ROLLER', 'TIER_4_WHALE_VAULTS']; // Unlimited
}

/**
 * RD-01: Fury Accuracy Calculation
 * Evaluates how trustworthy a peer reviewer is.
 */
export const FALSE_ACCUSATION_WEIGHT = 3;

export function calculateAccuracy(history: FuryHistory): number {
  if (history.totalAudits === 0) return 1.0; // Benefit of doubt for new Furies

  // Weighted calculation mathematically punishing false claims 3x
  const netSuccess = history.successfulAudits - (history.falseAccusations * FALSE_ACCUSATION_WEIGHT);
  const ratio = netSuccess / history.totalAudits;

  // Clamp between 0.0 and 1.0
  return Math.max(0.0, Math.min(1.0, ratio));
}

/**
 * F-FURY-08: Reviewer Quality Weights
 * Determines the voting power of an auditor based on their reputation.
 */
export function calculateReviewerWeight(history: FuryHistory): number {
  const accuracy = calculateAccuracy(history);
  
  // Master Tier: >200 audits, >= 95% accuracy
  if (history.totalAudits >= 200 && accuracy >= 0.95) return 2.0;
  
  // Journeyman Tier: >50 audits, >= 90% accuracy
  if (history.totalAudits >= 50 && accuracy >= 0.90) return 1.5;
  
  // Novice Tier: Default
  return 1.0;
}

export function shouldDemoteFury(history: FuryHistory): boolean {
  // Triggers demotion if accuracy falls below 80% after a 10 case burn-in period.
  if (history.totalAudits < 10) return false;
  return calculateAccuracy(history) < 0.8;
}

/**
 * Returns the maximum stake amount for a given set of allowed tiers.
 */
/**
 * Returns a display-friendly tier name for the frontend based on Integrity Score.
 */
export function getDisplayTier(score: number): string {
  if (score >= 500) return 'WHALE';
  if (score >= 100) return 'HIGH_ROLLER';
  if (score >= 50) return 'STANDARD';
  if (score >= 20) return 'MICRO';
  return 'RESTRICTED';
}

/** Returns the maximum stake amount in cents for a given set of allowed tiers. */
export function getTierMaxStake(tiers: string[]): number {
  if (tiers.includes('TIER_4_WHALE_VAULTS')) return Infinity;
  if (tiers.includes('TIER_3_HIGH_ROLLER')) return 100000; // $1,000
  if (tiers.includes('TIER_2_STANDARD')) return 10000; // $100
  if (tiers.includes('TIER_1_MICRO_STAKES')) return 2000; // $20
  return 0;
}


=== MONEY UTILITIES ===
File: src/shared/libs/money.ts

/**
 * Money utilities — all internal amounts are stored as integer cents.
 * Use toCents() at system boundaries (user input) and toDollars() for display.
 */

// Tolerance for IEEE-754 float error when deciding whether a dollar amount lands on a
// whole-cent boundary. $0.005 * 100 = 0.4999999... in binary; we treat anything within
// this epsilon of an integer cent as that integer cent (robust rounding), and reject
// anything that genuinely carries a fractional cent (e.g. $10.005, $19.999).
const CENT_EPSILON = 1e-6;

/**
 * Convert a dollar amount to integer cents.
 *
 * Throws if the input is not a finite number, OR if it does not represent a whole number
 * of cents (within float tolerance). Silently rounding fractional-cent inputs (the old
 * behavior) hides boundary/units bugs at money-handling sites, so they are surfaced instead.
 */
export function toCents(dollars: number): number {
  if (!Number.isFinite(dollars)) {
    throw new Error(\`toCents: expected a finite number, received \${dollars}\`);
  }
  const exactCents = dollars * 100;
  const rounded = Math.round(exactCents);
  if (Math.abs(exactCents - rounded) > CENT_EPSILON) {
    throw new Error(
      \`toCents: \${dollars} is not a whole number of cents (got \${exactCents}). \` +
        \`Round to the nearest cent before converting.\`,
    );
  }
  // Normalize -0 to 0 and return the epsilon-tolerant rounded integer.
  return rounded === 0 ? 0 : rounded;
}

/**
 * Convert integer cents to a dollar amount for display.
 * Validates that the input is a non-negative integer; internal amounts must never be
 * negative or fractional, so a sign/units error is surfaced rather than rendered.
 */
export function toDollars(cents: number): number {
  assertNonNegativeIntegerCents(cents, 'toDollars');
  return cents / 100;
}

/** Format cents as a dollar string (e.g., 4999 → "$49.99"). */
export function formatCents(cents: number): string {
  assertNonNegativeIntegerCents(cents, 'formatCents');
  return \`$\${(cents / 100).toFixed(2)}\`;
}

/** Guard that an amount is a non-negative integer number of cents. */
function assertNonNegativeIntegerCents(cents: number, fn: string): void {
  if (!Number.isInteger(cents)) {
    throw new Error(\`\${fn}: expected an integer number of cents, received \${cents}\`);
  }
  if (cents < 0) {
    throw new Error(\`\${fn}: expected a non-negative amount of cents, received \${cents}\`);
  }
}


=== DATABASE SCHEMA ===
File: src/api/database/schema.sql

-- ARC-07: Double-Entry Ledger Schema
-- Enforce absolute financial integrity for user stakes and bounties.

CREATE TYPE account_type AS ENUM ('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE');

CREATE TABLE accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    type account_type NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, QUARANTINED
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    debit_account_id UUID REFERENCES accounts(id) ON DELETE RESTRICT,
    credit_account_id UUID REFERENCES accounts(id) ON DELETE RESTRICT,
    -- Stored as integer cents to avoid floating-point drift.
    amount BIGINT NOT NULL CHECK (amount > 0),
    contract_id UUID,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE event_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type TEXT NOT NULL,
    payload JSONB NOT NULL,
    previous_hash TEXT NOT NULL,
    current_hash TEXT NOT NULL, -- hash(previous_hash || payload || created_at)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for rapid sequential verification of the chain.
CREATE INDEX idx_event_log_created_at ON event_log(created_at);

-- Immutability: prevent UPDATE/DELETE on event_log (append-only audit trail)
CREATE OR REPLACE FUNCTION prevent_event_log_mutation()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'event_log is immutable: UPDATE and DELETE are prohibited';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_event_log_immutable
  BEFORE UPDATE OR DELETE ON event_log
  FOR EACH ROW EXECUTE FUNCTION prevent_event_log_mutation();

-- ============================================================
-- Domain Tables: Users, Contracts, Proofs, Fury Assignments
-- ============================================================

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT,
    stripe_customer_id TEXT,
    integrity_score INTEGER DEFAULT 50,
    account_id UUID REFERENCES accounts(id),
    role TEXT DEFAULT 'USER',
    enterprise_id UUID,
    status TEXT DEFAULT 'ACTIVE', last_known_state TEXT, social_guild_id UUID,
    deletion_requested_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE contracts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id),
    oath_category TEXT NOT NULL,
    verification_method TEXT NOT NULL,
    stake_amount DECIMAL(19,4) NOT NULL CHECK (stake_amount > 0),
    payment_intent_id TEXT,
    duration_days INTEGER NOT NULL,
    status TEXT DEFAULT 'PENDING_STAKE',
    grace_days_used INTEGER DEFAULT 0,
    grace_period_month TEXT,
    strikes INTEGER DEFAULT 0,
    started_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Deferred FK: entries.contract_id references contracts (entries table defined before contracts)
ALTER TABLE entries ADD CONSTRAINT fk_entries_contract_id
  FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE RESTRICT;

-- Auto-update updated_at on row modification
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER contracts_updated_at
    BEFORE UPDATE ON contracts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- Recovery Stream: Accountability Partners & Daily Attestations
-- ============================================================

ALTER TABLE contracts ADD COLUMN metadata JSONB DEFAULT '{}';

CREATE TABLE accountability_partners (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES contracts(id) ON DELETE CASCADE,
    partner_user_id UUID REFERENCES users(id),
    partner_email TEXT,
    status TEXT DEFAULT 'PENDING',  -- PENDING, ACTIVE, VETOED
    invited_at TIMESTAMPTZ DEFAULT NOW(),
    accepted_at TIMESTAMPTZ
);

CREATE TABLE attestations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES contracts(id),
    user_id UUID REFERENCES users(id),
    attestation_date DATE NOT NULL,
    attested_at TIMESTAMPTZ,
    cosigned_by UUID REFERENCES users(id),
    cosigned_at TIMESTAMPTZ,
    status TEXT DEFAULT 'PENDING',  -- PENDING, ATTESTED, COSIGNED, MISSED
    UNIQUE(contract_id, attestation_date)
);

CREATE INDEX idx_attestations_contract_id ON attestations(contract_id);
CREATE INDEX idx_attestations_status ON attestations(status);
CREATE INDEX idx_accountability_partners_contract_id ON accountability_partners(contract_id);

CREATE TABLE proofs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES contracts(id),
    user_id UUID REFERENCES users(id),
    media_uri TEXT,
    proof_type TEXT DEFAULT 'MEDIA',  -- MEDIA, ATTESTATION
    is_honeypot BOOLEAN DEFAULT FALSE,
    honeypot_expected_verdict TEXT,  -- known-correct verdict for honeypots ('PASS'/'FAIL'); NULL for real proofs
    status TEXT DEFAULT 'PENDING_REVIEW',
    processing_status TEXT DEFAULT 'NOT_STARTED',
    challenge_token TEXT,
    metadata_hash TEXT,
    masked_media_uri TEXT,
    redaction_status TEXT DEFAULT 'NOT_APPLICABLE',
    redaction_profile TEXT,
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE fury_assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    proof_id UUID REFERENCES proofs(id),
    fury_user_id UUID REFERENCES users(id),
    verdict TEXT,
    reviewed_at TIMESTAMPTZ,
    assigned_at TIMESTAMPTZ DEFAULT NOW(),
    subject_alias TEXT
);

CREATE TABLE notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id),
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT,
    read BOOLEAN DEFAULT FALSE,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_unread ON notifications(user_id, read) WHERE read = FALSE;

-- Stripe webhook idempotency: track processed event IDs
CREATE TABLE stripe_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id TEXT UNIQUE NOT NULL,
    event_type TEXT NOT NULL,
    processed_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_stripe_events_event_id ON stripe_events(event_id);

CREATE TABLE contract_resolution_side_effects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES contracts(id) ON DELETE CASCADE,
    outcome TEXT NOT NULL,
    effect_type TEXT NOT NULL,
    dedupe_key TEXT NOT NULL UNIQUE,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    locked_at TIMESTAMPTZ,
    next_retry_at TIMESTAMPTZ,
    quarantined_at TIMESTAMPTZ,
    quarantine_reason TEXT,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT chk_contract_resolution_effect_status
      CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'QUARANTINED'))
);

CREATE INDEX idx_contract_resolution_effects_contract
  ON contract_resolution_side_effects(contract_id, created_at);
CREATE INDEX idx_contract_resolution_effects_status
  ON contract_resolution_side_effects(status, created_at);
CREATE INDEX idx_contract_resolution_effects_retry_due
  ON contract_resolution_side_effects(status, next_retry_at)
  WHERE status = 'FAILED';
CREATE INDEX idx_contract_resolution_effects_quarantined
  ON contract_resolution_side_effects(status, quarantined_at)
  WHERE status = 'QUARANTINED';

-- B2B Consumption Billing
CREATE TABLE consumption_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    enterprise_id UUID NOT NULL,
    event_type TEXT NOT NULL,
    units INTEGER NOT NULL DEFAULT 1,
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_consumption_logs_enterprise_period
  ON consumption_logs(enterprise_id, recorded_at);
CREATE INDEX idx_consumption_logs_event_type
  ON consumption_logs(enterprise_id, event_type, recorded_at);

CREATE INDEX idx_contracts_user_id ON contracts(user_id);
CREATE INDEX idx_contracts_status ON contracts(status);
CREATE INDEX idx_proofs_contract_id ON proofs(contract_id);
CREATE INDEX idx_proofs_status ON proofs(status);
CREATE INDEX idx_fury_assignments_proof_id ON fury_assignments(proof_id);
CREATE INDEX idx_fury_assignments_fury_user_id ON fury_assignments(fury_user_id);

-- Ledger performance indexes
-- Refresh tokens for JWT rotation
CREATE TABLE refresh_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_token_hash ON refresh_tokens(token_hash);

-- Account lockout columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;

CREATE INDEX idx_entries_debit_account_id ON entries(debit_account_id);
CREATE INDEX idx_entries_credit_account_id ON entries(credit_account_id);
CREATE INDEX idx_entries_contract_id ON entries(contract_id);
CREATE INDEX idx_users_enterprise_id ON users(enterprise_id);
CREATE INDEX idx_users_deletion_requested_at ON users(deletion_requested_at);

CREATE INDEX idx_users_last_known_state ON users(last_known_state);
CREATE INDEX idx_users_social_guild_id ON users(social_guild_id);

-- Real-money settlement tracking (TKT-P0-001)
CREATE TABLE IF NOT EXISTS settlement_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES contracts(id),
    outcome TEXT NOT NULL,
    amount_cents INTEGER NOT NULL,
    status TEXT NOT NULL, -- PROCESSING, SUCCESS, FAILED
    disposition_mode TEXT, -- CAPTURE, REFUND
    quote_json JSONB, -- Deterministic payout breakdown
    provider_tx_id TEXT,
    last_error TEXT,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_settlement_runs_contract_id ON settlement_runs(contract_id);
CREATE INDEX IF NOT EXISTS idx_settlement_runs_status ON settlement_runs(status);

-- Settlement auditability indexes for ledger entries
CREATE INDEX IF NOT EXISTS idx_entries_settlement_run_id ON entries ((metadata->>'settlement_run_id'));
CREATE INDEX IF NOT EXISTS idx_entries_provider ON entries ((metadata->>'provider'));

-- Phase Gamma: Trust Chain (TKT-P1-007, TKT-P1-013, TKT-P1-014)

CREATE TABLE IF NOT EXISTS health_oracle_samples (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id),
    contract_id UUID REFERENCES contracts(id),
    source_bundle_id TEXT NOT NULL,
    was_user_entered BOOLEAN NOT NULL DEFAULT FALSE,
    sample_hash TEXT NOT NULL UNIQUE,
    accepted BOOLEAN NOT NULL,
    reason TEXT,
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_health_oracle_samples_user_id ON health_oracle_samples(user_id);

CREATE TABLE IF NOT EXISTS proof_processing_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    proof_id UUID REFERENCES proofs(id),
    stage TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'QUEUED',
    attempts INTEGER DEFAULT 0,
    worker_ref TEXT,
    error TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proof_processing_jobs_proof_id ON proof_processing_jobs(proof_id);
-- Migration 021: Phase Gamma Enforcement and Recovery (TKT-P1-015, TKT-P1-005)

-- TKT-P1-015: Collusion Slashing
CREATE TABLE IF NOT EXISTS fury_enforcement_cases (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reviewer_id UUID REFERENCES users(id),
    case_type TEXT NOT NULL, -- HONEYPOT_FAILURE, COLLUSION_RING
    confidence FLOAT NOT NULL,
    status TEXT DEFAULT 'PENDING_REVIEW', -- PENDING_REVIEW, PENALTY_APPLIED, APPEALED, REVERSED
    evidence_json JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fury_enforcement_cases_reviewer ON fury_enforcement_cases(reviewer_id);

CREATE TABLE IF NOT EXISTS fury_penalties (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id UUID REFERENCES fury_enforcement_cases(id),
    penalty_type TEXT NOT NULL, -- STAKE_SLASH, REP_BURN, BAN
    amount_cents INTEGER,
    applied_at TIMESTAMPTZ DEFAULT NOW(),
    reversed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_fury_penalties_case ON fury_penalties(case_id);

-- TKT-P1-005: Recovery Timelock
CREATE TABLE IF NOT EXISTS recovery_break_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES contracts(id),
    requested_at TIMESTAMPTZ DEFAULT NOW(),
    unlock_at TIMESTAMPTZ NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'PENDING_COOLDOWN' -- PENDING_COOLDOWN, UNLOCKED, CANCELLED, CONSUMED
);
CREATE INDEX IF NOT EXISTS idx_recovery_break_requests_contract ON recovery_break_requests(contract_id);
-- Migration 022: Weekend Multiplier Policy (TKT-P1-012)

CREATE TABLE IF NOT EXISTS contract_penalty_windows (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES contracts(id),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    multiplier FLOAT NOT NULL DEFAULT 2.0,
    source_policy TEXT NOT NULL -- WEEKEND_RELAPSE_PREVENTION
);
CREATE INDEX IF NOT EXISTS idx_contract_penalty_windows_contract ON contract_penalty_windows(contract_id);

-- Migration 023: Accountability Partner Protocol (TKT-P1-017)

CREATE TABLE IF NOT EXISTS accountability_partner_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES contracts(id),
    actor_id UUID REFERENCES users(id),
    event_type TEXT NOT NULL, -- INVITE_SENT, INVITE_ACCEPTED, INVITE_DECLINED, VETO_TRIGGERED
    payload JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE accountability_partners 
ALTER COLUMN status TYPE TEXT,
ALTER COLUMN status SET DEFAULT 'PENDING';

-- Ensure status is one of: PENDING, ACTIVE, DECLINED, REVOKED

-- Migration 024: Goal-Gradient Dashboard and Live Leaderboard (TKT-P1-018)

CREATE TABLE IF NOT EXISTS leaderboard_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id),
    score_delta INTEGER NOT NULL,
    reason TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_leaderboard_events_user ON leaderboard_events(user_id);

CREATE TABLE IF NOT EXISTS dashboard_progress_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id),
    snapshot_date DATE NOT NULL DEFAULT CURRENT_DATE,
    payload_json JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, snapshot_date)
);

-- Migration 025: Realms — Portal-Based Behavioral Domain Separation

CREATE TABLE IF NOT EXISTS realms (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    stream_prefix TEXT NOT NULL,
    config JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO realms (id, name, slug, stream_prefix, config) VALUES
  ('BIOLOGICAL_HARDWARE',  'Biological Hardware',  'biological-hardware',  'BIOLOGICAL',   '{}'),
  ('COGNITIVE_DEVICE',     'Cognitive Device',     'cognitive-device',     'COGNITIVE',    '{}'),
  ('PROFESSIONAL_API',     'Professional API',     'professional-api',     'PROFESSIONAL', '{}'),
  ('CREATIVE_PROCESS',     'Creative Process',     'creative-process',     'CREATIVE',     '{}'),
  ('ENVIRONMENTAL_VISUAL', 'Environmental Visual', 'environmental-visual', 'VISUAL',       '{}'),
  ('CHARACTER_SOCIAL',     'Character Social',     'character-social',     'SOCIAL',       '{}'),
  ('RECOVERY_ABSTINENCE',  'Recovery Abstinence',  'recovery-abstinence',  'RECOVERY',     '{}')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE contracts ADD COLUMN IF NOT EXISTS realm_id TEXT REFERENCES realms(id);
CREATE INDEX IF NOT EXISTS idx_contracts_realm_id ON contracts(realm_id);

CREATE TABLE IF NOT EXISTS fury_realm_expertise (
    fury_user_id UUID REFERENCES users(id),
    realm_id TEXT REFERENCES realms(id),
    audits_completed INTEGER DEFAULT 0,
    accuracy FLOAT DEFAULT 1.0,
    specialization_level TEXT DEFAULT 'NOVICE',
    PRIMARY KEY (fury_user_id, realm_id)
);

ALTER TABLE fury_assignments ADD COLUMN IF NOT EXISTS realm_id TEXT REFERENCES realms(id);
CREATE INDEX IF NOT EXISTS idx_fury_assignments_realm_id ON fury_assignments(realm_id);

ALTER TABLE users ADD COLUMN IF NOT EXISTS realm_preferences JSONB DEFAULT '{}';



=== FEATURE BACKLOG (executive summary + P0/P1) ===
File: docs/FEATURE-BACKLOG.md

# Styx Feature Backlog: Documentation → Implementation

**Version**: 1.4.0
**Generated**: 2026-02-28
**Codebase Baseline**: v0.8.0 (1,107 tests, 6 workspaces)
**Source Documents Ingested**: 37 markdown files across research, architecture, legal, planning, and brainstorm categories

---

## Executive Summary

### Status Breakdown

| Status | Count | Description |
|--------|-------|-------------|
| IMPLEMENTED | 23 | Working code with tests |
| PARTIAL | 12 | Code exists but incomplete or conditional |
| STUB | 1 | Files/endpoints exist but placeholder logic |
| NOT_STARTED | 44 | Described in docs, no code |
| **Total** | **78** | |

### P0: Beta Blockers (Must-Build for Phase 1 Private Beta)

| ID | Feature | Status | Blocker Reason |
|----|---------|--------|----------------|
| F-MOBILE-01 | Native iOS Camera Module | STUB | Cannot verify proofs without native capture |
| F-CORE-04 | Real-Money Stripe FBO Settlement | PARTIAL | Test-money only; need FBO routing for beta |
| F-AEGIS-03 | Age Gate (18+ Runtime) | IMPLEMENTED | Legal requirement for financial stakes |
| F-VERIFY-06 | Attestation Daily Flow (No-Contact) | IMPLEMENTED | Primary Phase 1 journey depends on this |
| F-WEB-01 | HttpOnly Cookie Auth Migration | IMPLEMENTED | Security requirement before public beta |
| F-LEGAL-01 | Contest Official Rules Engine | IMPLEMENTED | Every contest needs official rules per law |

### P1: Beta Enhancers (Should-Build for Phase 1)

| ID | Feature | Status |
|----|---------|--------|
| F-VERIFY-02 | HealthKit Native Bridge (iOS) | NOT_STARTED |
| F-UX-01 | Identity-Based Onboarding | NOT_STARTED |
| F-UX-03 | Dynamic Downscale Intervention | PARTIAL |
| F-FURY-03 | Cross-Lobby Auditing | NOT_STARTED |
| F-AEGIS-04 | Recovery Protocol Guardrails | PARTIAL |
| F-MOBILE-03 | Push Notifications | PARTIAL |
| F-SOCIAL-07 | Pod-Based Cohorts (Max 5) | NOT_STARTED | New for March 6 Launch |
| F-SOCIAL-08 | Pod-Level Visibility (Active/Out) | NOT_STARTED | Real-time failure broadcast within pod |
| F-SOCIAL-09 | Anonymous Peer Disclosure (First Name) | NOT_STARTED | Pod-only identity for accountability |
| F-FIN-05 | $39 Entry Model ($9 Fee + $30 Stake) | NOT_STARTED | Standardized MVP pricing |
| F-VERIFY-17 | Binary Daily Check-in (Self-Report) | NOT_STARTED | Initial verification fallback for MVP |
| F-VERIFY-15 | Whoop SCORED State Webhooks | NOT_STARTED | Part of Blockchain of Truth v2 |
| F-VERIFY-16 | HealthKit Metadata WasUserEntered | NOT_STARTED | Part of Blockchain of Truth v2 |

### P2: Post-Beta (Phase 2+)

Features that enhance but don't block: PvP lobbies, spectator markets, Plaid integration, B2B therapist dashboard, prediction markets, maintenance pools, referral system, and more (~30 features).

### P3: Future / Research-Only

Advanced features requiring external dependencies or significant R&D: EVM smart contracts, ZKP privacy layer, DECO oracles, brain-computer interfaces, hardware partnerships (~15 features).

### Critical Path: Phase 1 Private Beta

\`\`\`
[Aegis Protocol] ──→ [Age Gate 18+] ──→ [Contest Rules] ──→ [Real-Money FBO]
        │                                                          │
        ↓                                                          ↓
[Native Camera] ──→ [Attestation Flow] ──→ [HttpOnly Auth] ──→ [TestFlight]
\`\`\`

---

## Part I: Full Feature Catalog by Domain

---

### Domain 1: CORE — Ledger, Escrow, Financial Infrastructure

#### F-CORE-01: Double-Entry Ledger Engine

- **Status**: IMPLEMENTED
- **Phase**: Alpha
- **Priority**: P0 (foundation)

=== IMPLEMENTATION STATUS (claim-to-control matrix) ===
File: docs/planning/planning--implementation-status.md

# Implementation Status (Claim-to-Control Matrix)

This document maps high-level product/security/compliance claims to their current implementation status.

Statuses:
- \`Implemented\`: Runtime control exists and is exercised in code/tests.
- \`Partial\`: Control exists but behavior is incomplete, conditional, or environment-dependent.
- \`Planned\`: Documented policy/intent only; runtime control not yet implemented.
- \`Research\`: External analysis or exploratory content; not product policy.

| Claim | Source | Status | Code Paths | Tests / Evidence | Owner |
|---|---|---|---|---|---|
| Global + endpoint-specific rate limiting (\`@nestjs/throttler\`) | \`README.md\`, \`SECURITY.md\` | Implemented | \`/src/api/src/app.module.ts\`, \`/src/api/src/modules/auth/auth.controller.ts\`, \`/src/api/src/modules/contracts/contracts.controller.ts\`, \`/src/api/src/modules/proofs/proofs.controller.ts\` | Typechecked + API route decorators in source | API |
| JWT secret required in production | \`README.md\`, \`SECURITY.md\` | Implemented | \`/src/api/src/modules/auth/auth.service.ts\`, \`/src/api/src/main.ts\` | \`/src/api/src/modules/auth/auth.service.spec.ts\` (token behavior) | API |
| JWT has no fallback secret | \`SECURITY.md\` (old wording) | Partial | \`/src/api/src/modules/auth/auth.service.ts\` (dev/test fallback remains) | Code inspection | API |
| Geofencing by jurisdiction tier | \`README.md\`, \`SECURITY.md\` | Partial | \`/src/api/services/geofencing.ts\`, \`/src/api/src/common/guards/geofence.guard.ts\`, \`/src/api/src/modules/compliance/compliance-policy.service.ts\` | \`/src/api/src/common/guards/geofence.guard.spec.ts\` | API / Compliance |
| \`TIER_2\` refund-only restrictions on monetary-risk actions | Plan / runtime policy | Implemented (initial scope) | \`/src/api/src/modules/compliance/compliance-policy.service.ts\` | \`/src/api/src/common/guards/geofence.guard.spec.ts\` | API / Compliance |
| \`x-styx-state\` geofence override header is test-only (non-production) | Plan / runtime policy | Implemented | \`/src/api/src/modules/compliance/compliance-policy.service.ts\`, \`/src/api/src/common/guards/geofence.guard.ts\` | \`/src/api/src/common/guards/geofence.guard.spec.ts\` | API / Compliance |
| Missing geolocation headers default fail-open (configurable) | Plan / runtime policy | Implemented | \`/src/api/src/modules/compliance/compliance-policy.service.ts\`, \`.env.example\` | \`/src/api/src/common/guards/geofence.guard.spec.ts\` | API / Compliance |
| KYC / identity verification runtime enforcement | \`docs/legal/legal--aegis-protocol.md\` | Planned | (No runtime enforcement yet; reserved flag \`KYC_ENFORCEMENT_ENABLED\`) | \`.env.example\`, \`/src/api/src/modules/compliance/compliance-policy.service.ts\` capability flag | Compliance / Platform |
| Age 18+ strict enforcement | \`docs/legal/legal--aegis-protocol.md\` | Implemented | \`/src/api/src/modules/auth/auth.service.ts\` (register validation), \`/src/api/database/migrations/008_age_gate_terms_acceptance.sql\`, \`/src/web/app/register/page.tsx\`, \`/src/mobile/screens/RegisterScreen.tsx\` | \`/src/api/src/modules/auth/auth.service.spec.ts\` | Compliance / Product |
| Web auth uses HttpOnly cookie JWTs | \`src/web/README.md\` | Implemented | \`/src/web/contexts/AuthContext.tsx\`, \`/src/web/services/api-client.ts\` | Code inspection; cookies set with httpOnly flag | Web |
| Web auth is client-side JWT today | Current runtime | Implemented | \`/src/web/contexts/AuthContext.tsx\`, \`/src/web/services/api-client.ts\`, \`/src/web/proxy.ts\` | Web typecheck (\`/src/web\`), runtime code path | Web |
| Sentry error monitoring | Operational requirement | Implemented | \`/src/api/src/main.ts\` (Sentry.init), \`/src/web/app/error.tsx\`, \`/src/api/src/common/monitoring/\` | Runtime integration; error boundaries in web | Platform |
| Daily attestation flow (Recovery stream) | \`planning--phase1-private-beta-scope.md\` | Implemented | \`/src/api/src/modules/contracts/contracts.service.ts\` (getAttestationStatus, submitAttestation), \`/src/api/src/modules/contracts/contracts.controller.ts\`, \`/src/web/app/contracts/[id]/attest/page.tsx\`, \`/src/mobile/screens/AttestationScreen.tsx\` | \`/src/api/src/modules/contracts/contracts.service.spec.ts\` | Product |
| Cohort snapshot API (roster, Active/Out, pod breakdown) | \`planning--meeting-notes--2026-02.md\`, \`planning--roadmap.md\` | Implemented | \`/src/api/src/modules/contracts/contracts.controller.ts\` (\`GET /contracts/cohorts/:cohortId/snapshot\`), \`/src/api/src/modules/contracts/contracts.service.ts\` (\`getCohortSnapshot\`) | \`/src/api/src/modules/contracts/contracts.controller.spec.ts\`, \`/src/api/src/modules/contracts/contracts.service.spec.ts\` | API / Product |
| Cohort enrollment guardrails (pod required for POD_BASED, max pod size 5, cohort capacity checks) | \`planning--meeting-notes--2026-02.md\`, \`planning--roadmap--mvp-drive.md\` | Implemented | \`/src/api/src/modules/contracts/dto.ts\` (\`CohortEnrollmentDto\`), \`/src/api/src/modules/contracts/contracts.service.ts\` (\`buildCohortMetadata\`) | \`/src/api/src/modules/contracts/contracts.service.spec.ts\`, \`/src/api/src/modules/contracts/contracts.controller.spec.ts\` | API / Product |
| MVP pricing plan metadata (\`MVP_39\` = \`$39\` total, \`$9\` platform fee, \`$30\` refundable stake) | \`planning--roadmap--mvp-drive.md\`, \`brainstorm--transcript--2026-02-27.md\` | Implemented (metadata + stake enforcement) | \`/src/api/src/modules/contracts/dto.ts\` (\`PricingPlan\`), \`/src/api/src/modules/contracts/contracts.service.ts\` (\`normalizeContractPricing\`) | \`/src/api/src/modules/contracts/contracts.service.spec.ts\`, \`/src/api/src/modules/contracts/contracts.controller.spec.ts\` | API / Product |
| Whoop SCORED ingestion endpoint for recovery contracts | \`planning--roadmap.md\`, \`docs/research/research--smart-contracts-behavioral-wagers-v2.md\` | Implemented (initial API path) | \`/src/api/src/modules/contracts/contracts.controller.ts\` (\`POST /contracts/:id/whoop/scored\`), \`/src/api/src/modules/contracts/contracts.service.ts\` (\`submitWhoopScoredState\`) | \`/src/api/src/modules/contracts/contracts.service.spec.ts\`, \`/src/api/src/modules/contracts/contracts.controller.spec.ts\` | API |
| HealthKit manual-entry filter utility (\`HKMetadataKeyWasUserEntered\`) | \`docs/research/research--app-verification-tech-privacy-law.md\`, \`docs/planning/planning--roadmap.md\` | Implemented (guard utility, bridge integration still pending) | \`/src/mobile/services/HealthKitMetadataGuard.ts\` | \`/src/mobile/services/HealthKitMetadataGuard.spec.ts\` | Mobile |
| Contest official rules published | \`docs/legal/legal--compliance-guardrails.md\` §4.C | Implemented | \`/src/web/app/legal/rules/page.tsx\` | Web build; route \`/legal/rules\` | Legal |
| Responsible use disclosures published | \`docs/legal/legal--compliance-guardrails.md\` §4.E | Implemented | \`/src/web/app/legal/responsible-use/page.tsx\` | Web build; route \`/legal/responsible-use\`; links to NCPG, SAMHSA, NEDA, NDVH | Legal |
| Site-wide footer with legal page links | UX / compliance discoverability | Implemented | \`/src/web/components/SiteFooter.tsx\`, \`/src/web/app/layout.tsx\` | Web build; all 4 legal routes linked in footer | Web |
| Legal pages cross-linked ("Related Policies") | UX / compliance discoverability | Implemented | \`/src/web/app/legal/terms/page.tsx\`, \`/src/web/app/legal/privacy/page.tsx\`, \`/src/web/app/legal/rules/page.tsx\`, \`/src/web/app/legal/responsible-use/page.tsx\` | Web build; each page links to the other 3 | Web / Legal |
| Push notifications (local scheduling) | \`research--behavioral-engineering-masters.md\` | Partial | \`/src/mobile/services/NotificationService.ts\` (expo-notifications), \`/src/mobile/services/ApiClient.ts\` (registerPushToken) | \`/src/mobile/services/NotificationService.spec.ts\`; graceful degradation when package unavailable | Mobile |
| Mobile deep linking (styx:// URL scheme) | UX / push notification routing | Implemented | \`/src/mobile/config/linking.ts\` (LinkingOptions + resolveNotificationDeepLink), \`/src/mobile/App.tsx\` (NavigationContainer linking prop + notification tap handler) | \`/src/mobile/config/linking.spec.ts\` (18 tests) | Mobile |
| Endpoint smoke tests (staging + beta) | Operational / CI | Implemented | \`/scripts/smoke/check-endpoints.sh\`, \`/scripts/smoke/staging-smoke.sh\`, \`/scripts/smoke/beta-smoke.sh\` | Script validates health, auth guards, public routes, rate limiting, legal pages | Platform |
| Unified beta readiness contract + artifact (\`beta-readiness-summary.json\`) | Phase 1 release operations | Implemented | \`/scripts/smoke/beta-readiness.sh\`, \`/docs/planning/planning--beta-readiness-contract.md\`, \`/.github/workflows/ci.yml\` | \`npm run beta:readiness\` emits \`artifacts/beta-readiness-summary.json\`; CI uploads artifact in \`beta_readiness\` job | Platform |
| B2B consumption billing (real DB queries) | \`architecture--feasibility-stack.md\` | Implemented | \`/src/api/services/b2b/billing.service.ts\` (consumption_logs table), \`/src/api/database/schema.sql\` | \`/src/api/services/b2b/billing.service.spec.ts\` | API / B2B |
| CRM service (Salesforce/HubSpot connectors) | B2B integration | Implemented | \`/src/api/services/b2b/crm.service.ts\` (graceful fallback) | \`/src/api/services/b2b/crm.service.spec.ts\` | API / B2B |
| Desktop component test coverage | Quality / CI | Implemented | \`/src/desktop/src/components/LedgerInspector.spec.tsx\`, \`/src/desktop/src/components/MacroReview.spec.tsx\` (+ 5 more) | 128 tests across LedgerInspector, MacroReview, ExilePanel, B2BOrchestration, HashCollider, NetworkGuard, LoginScreen | Desktop |
| Web page + component test coverage | Quality / CI | Implemented | \`/src/web/app/dashboard/page.test.tsx\`, \`/src/web/components/SiteFooter.test.tsx\` (+ 25 more) | 166 tests across 27 suites (all pages + key components) | Web |
| Notifications controller spec | Quality / CI | Implemented | \`/src/api/src/modules/notifications/notifications.controller.spec.ts\` | Controller-level test coverage for notifications module | API |
| Legal compliance guardrails long-form memo is product policy | \`docs/legal/legal--compliance-guardrails.md\` (old presentation) | Research | \`/docs/legal/legal--compliance-guardrails.md\` | Labeled as research memo | Compliance |

## Notes

- Use \`/src/api/src/modules/compliance/compliance-policy.service.ts\` as the canonical place for request-level jurisdiction policy decisions.
- Update this matrix in the same PR whenever \`README.md\`, \`SECURITY.md\`, or legal policy docs change claim wording.
- When KYC/age verification is implemented, upgrade the corresponding rows from \`Planned\` to \`Implemented\` only after tests and rollout controls are merged.


=== PHASE 1 PRIVATE BETA SCOPE ===
File: docs/planning/planning--phase1-private-beta-scope.md

# Phase 1 Private Beta Scope (Mobile-First iOS)

This document is the scope lock for the first ship-ready private beta.

## Phase 1 Contract

- **Primary user surface**: iOS mobile app (TestFlight external beta)
- **Primary journey**: No-Contact recovery contracts
- **Money mode**: Test-money pilot (realistic hosted infra, no real-money settlement)
- **Region**: US allowlist only
- **Web role**: Admin/support companion (internal/operator workflows)
- **Desktop role**: Internal judge tool only
- **B2B/HR features**: Internal demo only (not tester-facing)

## Required Product Cuts

- Non-recovery contract categories may exist in code but are hidden or deprioritized in Phase 1 UX.
- Broad consumer web parity is explicitly deferred to Phase 2.
- Android formal beta distribution is deferred to Phase 2 unless iOS/TestFlight is blocked.
- KYC / age runtime enforcement remains out of scope for Phase 1 and must be clearly labeled as not active.

## Beta Labels (User-Facing)

All tester-facing surfaces should clearly communicate:

- \`Private Beta\`
- \`Test-Money Pilot\`
- \`US Allowlist\`

## Internal-Only Surfaces

The following are operator/internal-only in Phase 1:

- Web admin/support operations
- Desktop judge/dispute workflows
- B2B/HR demo flows

## Change Control

Any PR that expands tester-facing scope beyond this document must:

- update this file,
- update \`docs/planning/planning--implementation-status.md\` if claims change,
- update \`docs/planning/planning--beta-readiness-contract.md\` if release gates or readiness policy change,
- include an explicit rationale for the scope change.

## Readiness Source of Truth

Phase 1 release go/no-go is defined by \`docs/planning/planning--beta-readiness-contract.md\`.

- Operational checks must run via \`npm run beta:readiness\`.
- The generated artifact at \`artifacts/beta-readiness-summary.json\` is the canonical evidence format.


=== PROJECT METADATA (seed.yaml) ===
File: seed.yaml

# seed.yaml — Automation Contract for organvm-iii-ergon/peer-audited--behavioral-blockchain
# Schema: seed/v1.0
# Updated: 2026-03-11 (organ-chain-reset: real edges replace boilerplate)

schema_version: "1.0"
organ: III
organ_name: Commerce
repo: peer-audited--behavioral-blockchain
org: organvm-iii-ergon

metadata:
  implementation_status: ACTIVE
  tier: flagship
  promotion_status: PUBLIC_PROCESS
  last_validated: "2026-03-11"
  generated: "2026-02-22"
  language: typescript
  tags: [nestjs, nextjs, react-native, tauri, stripe, groq, llama, postgresql, redis]

agents:
  - name: ci
    trigger: on_push
    workflow: .github/workflows/ci.yml
    description: "Continuous integration pipeline"
  - name: governance-auditor
    trigger: schedule
    workflow: .github/workflows/blocked-handoff-burndown.yml
    description: "Weekly automated audit and index generation for blocked handoffs"
  - name: governance-intake
    trigger: on_issue
    workflow: .github/workflows/blocked-handoff-intake.yml
    description: "Normalizes blocked handoff metadata during issue intake"

consumes:
  - type: theory
    source: organvm-i-theoria/styx-behavioral-economics-theory
    description: "Behavioral economics models (loss aversion coefficient 1.955, prospect theory) and game-theoretic peer audit proofs"
  - type: creative-artifact
    source: organvm-ii-poiesis/styx-behavioral-art
    description: "Artistic visualization of stake/commitment/audit cycles informing UX design"
  - type: governance-rules
    source: organvm-iv-taxis/orchestration-start-here
    description: "CI/CD and promotion governance rules"

produces:
  - type: product
    description: "Styx: peer-audited behavioral market platform (NestJS API, Next.js web, React Native mobile, Tauri desktop)"
  - type: community_signal
    description: "Product milestones trigger community events"
    consumers: [organvm-vi-koinonia/community-hub]
  - type: distribution_signal
    description: "Releases trigger POSSE distribution"
    consumers: [organvm-vii-kerygma/kerygma-pipeline]
  - type: essay_material
    description: "Development milestones feed essay topics"
    consumers: [organvm-v-logos/essay-pipeline]

subscriptions:
  - event: theory.updated
    source: organvm-i-theoria/styx-behavioral-economics-theory
    action: Review theory changes for product implications
  - event: governance.updated
    source: ORGAN-IV
    action: Check compliance with updated governance rules
  - event: community.event_created
    source: ORGAN-VI
    action: Community event registered for this product
  - event: distribution.dispatched
    source: ORGAN-VII
    action: Announcement distributed via POSSE pipeline
`;
