// AUTO-GENERATED by scripts/build-chat-context.ts — do not edit manually.
// Regenerate with: npx tsx scripts/build-chat-context.ts

export const STYX_KNOWLEDGE = `=== PROJECT OVERVIEW (CLAUDE.md) ===
File: CLAUDE.md

# CLAUDE.md

This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository.

## What This Is

**Styx** ("The Blockchain of Truth") — a peer-audited behavioral market that uses loss aversion (coefficient 1.955) to enforce habit follow-through via financial stakes. Users stake money into behavioral contracts; a decentralized "Fury" network audits compliance; hardware oracles and a double-entry ledger enforce integrity.

Turborepo monorepo in ORGAN-III (commercial products). Promotion status: **PUBLIC_PROCESS**.

## Build & Dev Commands

All commands run from the repo root. Package manager: **npm** (not yarn/pnpm). Node >= 20.

\`\`\`bash
# First-time setup (Docker + install + build + test):
bash scripts/setup.sh

# Day-to-day:
make install          # npm install across all workspaces
make dev              # turbo run dev (API + Web + Mobile)
make build            # turbo run build
make test             # turbo run test
make docker-up        # docker-compose up -d (PostgreSQL + Redis)
npx turbo run lint    # strict TypeScript lint (tsc --noEmit per workspace)
npm run format        # prettier across all workspaces
npm run clean         # turbo clean + rm node_modules
\`\`\`

Individual workspace dev:
\`\`\`bash
cd src/api && npm run dev          # nest start --watch
cd src/web && npm run dev          # next dev -p 3001
cd src/mobile && npm start         # metro bundler (Expo)
cd src/mobile && npx expo run:ios  # iOS simulator
cd src/desktop && npm run dev      # vite dev
cd src/pitch && npm run dev        # vite dev (interactive pitch deck)
cd src/shared && npm run build     # tsc
cd src/api && npm run migrate      # run database migrations
\`\`\`

API docs (Swagger/OpenAPI): \`http://localhost:3000/api/docs\` when API is running.

### Testing

Jest + ts-jest in all workspaces (except pitch, which has no tests). Test files co-located as \`*.spec.ts\` (API, shared, mobile, desktop) or \`*.test.ts\`/\`*.test.tsx\` (web).

\`\`\`bash
make test                                                    # all workspaces via turbo
cd src/api && npx jest                                       # single workspace
cd src/api && npx jest services/ledger/ledger.service.spec.ts  # single file
cd src/api && npx jest --testNamePattern="should reject"      # single test by name
cd src/api && npx jest --coverage                             # with coverage report
\`\`\`

**Turbo pipeline**: \`"test": { "dependsOn": ["build"] }\` — \`@styx/shared\` must build before other workspaces can test against it.

**API coverage thresholds** (enforced in \`src/api/jest.config.cjs\`): lines 70%, branches 60%, functions 60%, statements 70%.

### E2E Tests (Playwright)

\`\`\`bash
make test-e2e                     # headless Playwright (chromium, firefox, webkit, mobile-chrome)
make test-e2e-ui                  # Playwright UI mode
npm run test:e2e:headed           # headed mode
\`\`\`

Config: \`.config/playwright/playwright.config.ts\`. Tests in \`e2e/\`. Base URL defaults to \`http://localhost:3001\`. Web server auto-starts via \`webServer\` config. E2E suites: auth, auth-guards, contract-lifecycle, dashboard, fury-workbench, recovery-contracts, wallet.

### Validation Gates

\`scripts/validation/\` — integration-level checks (Gates 04–07 run in CI):
1. \`01-phantom-money-check.ts\` — ledger prevents unbalanced entries
2. \`02-simulator-spoof-check.ts\` — hardware oracles reject manual data
3. \`03-the-full-loop.ts\` — end-to-end contract lifecycle
4. \`04-redacted-build-check.sh\` — no gambling terminology in production build (see also \`scripts/gatekeeper-scan.sh\`)
5. \`05-behavioral-physics-check.ts\` — core constants match spec (requires \`CI_GATE05_API_URL\` secret for live check)
6. \`06-security-invariant-check.ts\` — no hardcoded secrets or debug backdoors in production output
7. \`07-claim-drift-check.js\` — verifies file paths referenced in \`docs/planning/implementation-status.md\` still exist (\`npm run validate:claims\`)
8. \`08-fury-crucible-simulation.ts\` — Fury network simulation

### Smoke / Readiness Scripts

\`scripts/smoke/\` — deployment verification:
- \`beta-readiness.sh\` — comprehensive beta readiness suite (\`npm run beta:readiness\`); outputs \`artifacts/beta-readiness-summary.json\`
- \`check-endpoints.sh\`, \`check-api-ready.sh\`, \`check-api-release.sh\`, \`check-web.sh\` — individual endpoint checks
- \`vanguard-ignition.sh\` — vanguard deployment ignition

## Architecture

### Workspaces

| Workspace | Package | Stack | Role |
|-----------|---------|-------|------|
| \`src/api\` | \`@styx/api\` | NestJS 11, BullMQ, Stripe, pg, pino | Backend — ledger, escrow, Fury Router, oracles |
| \`src/web\` | \`@styx/web\` | Next.js 16, React 18, Tailwind, Zustand | Dashboard, Fury workbench |
| \`src/mobile\` | \`@styx/mobile\` | Expo 54, React Native 0.81, React Navigation 7 | Sensor bridge, camera, biometrics |
| \`src/shared\` | \`@styx/shared\` | TypeScript (pure) | Constants, types, algorithms |
| \`src/desktop\` | \`@styx/desktop\` | Tauri 2.0 beta, Vite, React | "The Judge" admin dashboard |
| \`src/pitch\` | \`@styx/pitch\` | Vite, React 18, p5.js, Tailwind | Interactive pitch deck (builds to \`docs/\` for GitHub Pages). No test/lint scripts. |

Path alias: \`@styx/shared/*\` → \`./src/shared/*\` (root \`tsconfig.json\`).

### API: Dual-Layer Structure

The API has **two parallel directory trees** — this is the most important structural detail:

- **\`src/api/services/\`** — Domain services (pure business logic, no HTTP). Each is an \`@Injectable()\` class with constructor-injected \`Pool\` or queue. These are the core building blocks.
- **\`src/api/src/modules/\`** — NestJS modules (controllers, route handlers, DI wiring). Each module imports domain services and exposes HTTP endpoints.

\`\`\`
src/api/
├── services/                    # Domain layer (business logic)
│   ├── ledger/                  #   Double-entry transactions, hash-chained audit log
│   ├── fury-router/             #   BullMQ proof routing, consensus engine
│   ├── escrow/                  #   Stripe FBO hold/capture/cancel, disputes
│   ├── health/                  #   Aegis protocol (BMI floor, velocity caps) + Recovery Protocol (no-contact guardrails)
│   ├── intelligence/            #   Honeypot injection, Gemini AI client
│   ├── security/                #   Geofencing, moderation (bans)
│   ├── anomaly/                 #   pHash duplicate detection, EXIF validation
│   ├── b2b/                     #   Enterprise B2B analytics
│   ├── storage/                 #   R2 service
│   ├── realtime/                #   SSE/WebSocket helpers
│   ├── billing.ts               #   Pricing constants
│   └── geofencing.ts            #   Jurisdiction tier enum + state map
├── src/modules/                 # NestJS application layer (HTTP + DI)
│   ├── auth/                    #   Login, register, JWT, enterprise SSO
│   ├── contracts/               #   CRUD, proof submission, grace days, scheduler
│   ├── compliance/              #   KYC/AML, eligibility checks
│   ├── fury/                    #   Queue, verdicts, bounty economy, stats
│   ├── wallet/                  #   Balance, transaction history
│   ├── b2b/                     #   Enterprise metrics, billing, webhooks, anonymization, data lake
│   ├── ai/                      #   Grill-me, ELI5, goal ethics screening
│   ├── admin/                   #   Moderation, honeypot management
│   ├── users/                   #   Profile, settings, scheduler
│   ├── notifications/           #   SSE stream, unread count, mark-read
│   ├── payments/                #   Stripe webhook handler
│   ├── proofs/                  #   Proof submission and verification
│   ├── oracles/                 #   Hardware oracle integration
│   ├── ledger/                  #   Ledger HTTP endpoints
│   ├── feed/                    #   Activity feed
│   ├── beta/                    #   Beta feature gates
│   └── health/                  #   Health check endpoint
├── guards/auth.guard.ts         # JWT auth guard
├── config/queue.config.ts       # Redis/BullMQ connection
└── database/schema.sql          # PostgreSQL schema (init script for docker)
\`\`\`

### Core Algorithms (\`src/shared/libs/\`)

**Integrity Score** (\`integrity.ts\`): \`Base(50) + 5*completions - 15*frauds - 20*strikes - 1*inactive_months\`. Floor at 0. Tier thresholds:
- \`RESTRICTED_MODE\` (score < 20): max stake $0
- \`TIER_1_MICRO_STAKES\` (< 50): max $20
- \`TIER_2_STANDARD\` (< 100): max $100
- \`TIER_3_HIGH_ROLLER\` (< 500): max $1,000
- \`TIER_4_WHALE_VAULTS\` (>= 500): unlimited

**Fury Accuracy** (\`integrity.ts\`): \`(successful - false_accusations*3) / total\`. Demotion at < 0.8 after 10-audit burn-in. Auditor stake: $2.00 per audit.

**Behavioral Logic** (\`behavioral-logic.ts\`): 7 oath categories (Biological, Cognitive, Professional, Creative, Environmental, Character, Recovery). Constants: grace days 2/month, onboarding bonus $5, loss aversion λ=1.955, downscale after 3 strikes, 7-day cool-off, BMI floor 18.5, 2% weekly loss velocity cap, recovery max 30 days, max 3 no-contact targets, 3 missed attestations = auto-fail.

**Money** (\`money.ts\`): Currency/amount utilities shared across workspaces.

### Web Routes

Next.js App Router: \`/\`, \`/dashboard\`, \`/fury\`, \`/wallet\`, \`/pitch\`, \`/hr\`, \`/tavern\`, \`/admin\`, \`/settings\`, \`/profile\`, \`/login\`, \`/register\`, \`/contracts/new\`, \`/contracts/[id]\`, \`/legal\`, \`/whistleblower\`.

**Linguistic Cloaker** (\`src/web/utils/linguistic-cloak.ts\`): Runtime vocabulary swap (stake→vault, bet→commitment, fury→peer review) for App Store/Stripe compliance.

### Mobile

Expo-managed React Native app. \`src/mobile/screens/\`: Dashboard, Login, Register, CreateContract, ContractList, ContractDetail, Fury, Wallet, Settings, Profile, Camera (placeholder — native Swift/Kotlin required).

\`src/mobile/services/\`: ApiClient (all endpoints), SessionService (AsyncStorage JWT), OfflineCache (TTL caching + mutation queue), UploadService (R2), NotificationService, EnterpriseSSO (deep links).

### Desktop Panels

\`src/desktop/src/panels/\`: LedgerInspector, MacroReview, ExilePanel, B2BOrchestration, LoginScreen.

### Infrastructure

- **Database**: PostgreSQL 15-alpine, double-entry ledger schema (\`src/api/database/schema.sql\`, seed: \`src/api/database/seed.sql\`)
- **Queue**: Redis 7-alpine + BullMQ (\`FURY_ROUTER_QUEUE\`)
- **Storage**: Cloudflare R2 (zero-egress, signed URLs only)
- **Payments**: Stripe FBO escrow (hold/capture/cancel)
- **AI (API services)**: Gemini 2.5 Flash (\`gemini-2.5-flash-preview-09-2025\`) for grill-me/ELI5
- **AI (Chat)**: Groq free tier + Llama 3.3 70B via OpenAI-compatible SDK (\`src/web/app/api/chat/route.ts\`). Configurable via \`GROQ_API_KEY\`, \`LLM_BASE_URL\`, \`LLM_MODEL\` env vars — works with any OpenAI-compatible endpoint (Groq, Together, Ollama, etc.)
- **CI**: GitHub Actions (\`ci.yml\`) — Node 20, security audit, turbo test + build + lint, Gates 04–07, beta readiness, Terraform validate, Playwright E2E (chromium + firefox), CodeQL
- **CD**: GitHub Actions (\`deploy.yml\`) — tag-triggered deploy to Render with smoke test. Also: \`beta-promotion.yml\`, \`staging-promotion.yml\`
- **IaC**: Terraform (\`infra/terraform/\`) — Render services, Cloudflare R2, WAF rules. Also \`scripts/infra/\` for R2 lifecycle, WAF rules, pg data lake extract
- **Render Blueprint**: \`render.yaml\` — API + Web + PostgreSQL + Redis (Oregon region, starter plan)
- **Docker**: \`.config/docker/docker-compose.yml\` (4 services: styx-api, styx-postgres, styx-redis, styx-web) and \`.config/docker/Dockerfile\` (API-only image)

### Key Design Constraints

- **Zero Trust**: All biometric/financial validation is server-side.
- **No Egress**: Media files never leave R2; serve only via signed URLs.
- **Stygian Terminology**: Fury=auditor, Vault=escrow, Oath=contract. Swap to neutral terms in app store builds via linguistic cloaker + gatekeeper scan.
- **Native bridges**: HealthKit/Google Fit must be native Swift/Kotlin — placeholder stubs in place, not yet implemented.

## Conventions

- **Commits**: Conventional Commits (\`feat:\`, \`fix:\`, \`docs:\`, \`chore:\`)
- **Branching**: \`feat/fury-bounty-ui\`, \`fix/ledger-race\`
- **Files**: kebab-case; double-hyphen separates function from descriptor (\`research--behavioral-economics.md\`)
- **TypeScript**: strict mode, named exports, async/await
- **NestJS testing pattern**: \`@Injectable()\` classes with constructor DI; mock \`Pool\` or service via \`as any\` cast in tests (see any \`*.spec.ts\` in \`src/api/src/modules/\`)

## Environment

Copy \`.env.example\` → \`.env\`. Required vars: \`STRIPE_SECRET_KEY\`, \`STRIPE_PUBLISHABLE_KEY\`, \`DATABASE_URL\`, \`REDIS_URL\`, \`CLOUDFLARE_R2_ACCESS_KEY\`, \`CLOUDFLARE_R2_SECRET_KEY\`, \`JWT_SECRET\`. Optional: \`GEMINI_API_KEY\`, \`ANONYMIZE_SALT\`, \`SENTRY_DSN\`, Salesforce/HubSpot keys.

Docker services: PostgreSQL \`5432\`, Redis \`6379\`, API \`3000\`, Web \`3001\`.

### Beta / Feature Flags

The \`.env\` includes a beta configuration system (all \`STYX_*\` and \`NEXT_PUBLIC_STYX_*\` prefixed):
- \`STYX_PRIVATE_BETA\` / \`STYX_TEST_MONEY_MODE\` — private beta mode with test money
- \`STYX_ALLOWLIST_US_ONLY\` — geofence to US only
- \`STYX_PHASE1_MOBILE_PRIMARY\` / \`STYX_PHASE1_NO_CONTACT_ONLY\` — Phase 1 scope limits
- \`STYX_FEATURE_B2B_HR_UI\` — enterprise HR dashboard toggle
- \`KYC_ENFORCEMENT_ENABLED\` / \`STYX_IDENTITY_PROVIDER\` — compliance toggles (mock provider in dev)

## Remaining Limitations

- **CameraModule**: Mobile camera requires native Swift/Kotlin — placeholder UI with text proof submission.
- **HealthKit/Google Fit**: Architectural stubs in \`src/mobile/services/\` but actual native bridges not implemented (requires Xcode/Android Studio).
- **High-risk merchant underwriting**: Business/legal process (Corepay/Allied Wallet application), not code.


=== BEHAVIORAL LOGIC (oath categories, constants, streams) ===
File: src/shared/libs/behavioral-logic.ts

/**
 * Behavioral Logic: The Kernel of Oaths & Physics
 * 
 * This file defines the exhaustive taxonomy of behaviors tracked by Styx.
 */

export enum OathCategory {
  // 1. Biological Stream (Hardware Oracle)
  WEIGHT_MANAGEMENT = "BIOLOGICAL_WEIGHT",
  CARDIOVASCULAR_STAMINA = "BIOLOGICAL_CARDIO",
  GLUCOSE_STABILITY = "BIOLOGICAL_METABOLIC",
  SLEEP_INTEGRITY = "BIOLOGICAL_SLEEP",
  SOBRIETY_HRV = "BIOLOGICAL_SOBRIETY",

  // 2. Cognitive Stream (Device Oracle)
  DIGITAL_FASTING = "COGNITIVE_DIGITAL",
  DEEP_WORK_FOCUS = "COGNITIVE_FOCUS",
  INBOX_ZERO = "COGNITIVE_QUEUE",
  LEARNING_RETENTION = "COGNITIVE_LEARNING",

  // 3. Professional Stream (API Oracle)
  SALES_VELOCITY = "PROFESSIONAL_SALES",
  DEVELOPER_THROUGHPUT = "PROFESSIONAL_CODE",
  PUNCTUALITY = "PROFESSIONAL_TIME",

  // 4. Creative Stream (The Muse) - Proof of Process
  DEEP_WRITING = "CREATIVE_WRITING",
  VISUAL_ARTS = "CREATIVE_ART",
  MUSIC_PRACTICE = "CREATIVE_MUSIC",
  MAKER_BUILD = "CREATIVE_BUILD",

  // 5. Environmental Stream (Fury Audited)
  NUTRITIONAL_TRANSPARENCY = "VISUAL_NUTRITION",
  TIDINESS_MINIMALISM = "VISUAL_ENVIRONMENT",
  PERSONAL_PRESENTATION = "VISUAL_IMAGE",
  ACTIVE_READING = "VISUAL_LITERACY",

  // 6. Character Stream (Multi-Oracle)
  CIVIC_ENGAGEMENT = "SOCIAL_COMMUNITY",
  PHILANTHROPIC_VELOCITY = "SOCIAL_CHARITY",
  FAMILY_PRESENCE = "SOCIAL_CONNECTION",

  // 7. Recovery Stream (Abstinence Oracle)
  NO_CONTACT_BOUNDARY = "RECOVERY_NOCONTACT",
  SUBSTANCE_ABSTINENCE = "RECOVERY_SUBSTANCE",
  BEHAVIORAL_DETOX = "RECOVERY_DETOX",
  ENVIRONMENT_AVOIDANCE = "RECOVERY_AVOIDANCE",
}

export enum VerificationMethod {
  HARDWARE_HEALTHKIT = "HEALTHKIT",
  HARDWARE_HEALTHCONNECT = "HEALTHCONNECT",
  API_SCREEN_TIME = "SCREENTIME",
  API_THIRD_PARTY = "EXTERNAL_API",
  FURY_CONSENSUS = "FURY_NETWORK",
  TIME_LAPSE = "TIME_LAPSE_PROOF", // For Creative Stream
  GPS_GEOFENCE = "GPS",
  FINANCIAL_LEDGER = "LEDGER",
  DAILY_ATTESTATION = "ATTESTATION",
}

export const MAX_GRACE_DAYS_PER_MONTH = 2;
export const ONBOARDING_BONUS_AMOUNT = 500; // cents ($5.00)

/**
 * AEGIS-04: Dispute Grace Period
 * Hours allowed to file a dispute before final stake liquidation.
 */
export const DISPUTE_GRACE_PERIOD_HOURS = 24;

/**
 * BE-01: Loss Aversion Anchor
 * Perceived pain of loss is ~2x pleasure of gain (λ = 1.955).
 * Reserved: Dynamic stake messaging (Phase Omega)
 */
export const LOSS_AVERSION_COEFFICIENT = 1.955;

/**
 * BE-05: Dynamic Downscaling Threshold
 */
export const DOWNSCALE_STRIKE_THRESHOLD = 3;

/**
 * CG-04: Cool-Off Period
 * Forced lockout days after a failure spree.
 */
export const FAILURE_COOL_OFF_DAYS = 7;

/**
 * AEGIS-01: Medical Guardrails
 */
export const MIN_SAFE_BMI = 18.5;
export const MAX_WEEKLY_LOSS_VELOCITY_PCT = 0.02;

/**
 * RECOVERY-01: Recovery Stream Guardrails
 * Forces re-evaluation cadence and prevents isolation patterns.
 */
export const MAX_NOCONTACT_DURATION_DAYS = 30;
export const MAX_NOCONTACT_TARGETS = 3;
export const NOCONTACT_MISS_STRIKE_THRESHOLD = 3;

/**
 * Oracle mapping: which verification methods are allowed for each oath stream.
 * BIOLOGICAL requires hardware oracles; COGNITIVE uses device APIs; etc.
 */
const OATH_METHOD_MAP: Record<string, VerificationMethod[]> = {
  BIOLOGICAL: [VerificationMethod.HARDWARE_HEALTHKIT, VerificationMethod.HARDWARE_HEALTHCONNECT],
  COGNITIVE: [VerificationMethod.API_SCREEN_TIME, VerificationMethod.API_THIRD_PARTY],
  PROFESSIONAL: [VerificationMethod.API_THIRD_PARTY, VerificationMethod.FINANCIAL_LEDGER],
  CREATIVE: [VerificationMethod.TIME_LAPSE, VerificationMethod.FURY_CONSENSUS],
  VISUAL: [VerificationMethod.FURY_CONSENSUS, VerificationMethod.GPS_GEOFENCE],
  SOCIAL: [VerificationMethod.FURY_CONSENSUS, VerificationMethod.GPS_GEOFENCE],
  RECOVERY: [VerificationMethod.DAILY_ATTESTATION, VerificationMethod.API_SCREEN_TIME, VerificationMethod.FURY_CONSENSUS],
};

/**
 * Validates that an oath category uses a correct oracle/verification method.
 * Returns true if the mapping is valid, false if the method is not allowed for the stream.
 */
export function validateOathMapping(category: OathCategory, method: VerificationMethod): boolean {
  const categoryValue = category as string;
  // Extract the stream prefix (e.g., "BIOLOGICAL" from "BIOLOGICAL_WEIGHT")
  const stream = categoryValue.split('_')[0];
  const allowedMethods = OATH_METHOD_MAP[stream];

  if (!allowedMethods) return false;
  return allowedMethods.includes(method);
}

export interface GraceDayResult {
  success: boolean;
  reason?: string;
  newDeadline?: Date;
}

/**
 * Uses one grace day for a contract — extends the deadline by 24 hours.
 * Caller must pass the current grace_days_used count and the current ends_at.
 * Returns the new deadline if successful, or a rejection reason.
 */
export function useGraceDay(
  graceDaysUsedThisMonth: number,
  currentEndsAt: Date,
): GraceDayResult {
  if (graceDaysUsedThisMonth >= MAX_GRACE_DAYS_PER_MONTH) {
    return { success: false, reason: \`Maximum \${MAX_GRACE_DAYS_PER_MONTH} grace days per month exceeded\` };
  }
  const newDeadline = new Date(currentEndsAt.getTime() + 24 * 60 * 60 * 1000);
  return { success: true, newDeadline };
}

export interface OnboardingBonusResult {
  granted: boolean;
  amount: number;
  reason?: string;
}

/**
 * Determines if a user qualifies for the onboarding bonus ($5 credit on first contract).
 * Caller must pass the user's total contract count.
 */
export function grantOnboardingBonus(totalContracts: number): OnboardingBonusResult {
  if (totalContracts > 0) {
    return { granted: false, amount: 0, reason: 'User already has prior contracts' };
  }
  return { granted: true, amount: ONBOARDING_BONUS_AMOUNT };
}

/**
 * DEPRECATED: Goal ethics screening has been moved to
 * src/api/services/intelligence/goal-ethics.service.ts
 * to fix the shared → api dependency inversion.
 * Import GoalEthicsService from the API layer instead.
 */

/** Active oath streams supported in MVP */
export const ACTIVE_OATH_STREAMS = [
  'BIOLOGICAL',
  'COGNITIVE',
  'PROFESSIONAL',
  'CREATIVE',
  'VISUAL',
  'SOCIAL',
  'RECOVERY',
] as const;

/** Check if an oath category is supported in the current MVP */
export function isOathStreamActive(category: OathCategory): boolean {
  const stream = (category as string).split('_')[0];
  return (ACTIVE_OATH_STREAMS as readonly string[]).includes(stream);
}


=== INTEGRITY SCORE (algorithm, tiers, Fury accuracy) ===
File: src/shared/libs/integrity.ts

export const BASE_INTEGRITY = 50;
export const FRAUD_PENALTY = 15;
export const STRIKE_PENALTY = 20;
export const COMPLETION_BONUS = 5;

export const AUDITOR_STAKE_AMOUNT = 200; // cents ($2.00)
export const AUDITOR_HARASSMENT_THRESHOLD = 3;

// Base Models
export interface UserHistory {
  userId: string;
  completedOaths: number;
  fraudStrikes: number;
  failedOaths: number;
  monthsInactive: number;
}

export interface FuryHistory {
  furyId: string;
  successfulAudits: number;
  falseAccusations: number;
  totalAudits: number;
}

/**
 * Calculates a user's Integrity Score (IS) based on behavioral physics.
 * Base (50) + (+5 per challenge) - (-15 per fraud) - (-20 per strike)
 * Also applies -1 point decay per inactive month.
 */
export function calculateIntegrity(history: UserHistory): number {
  const base = BASE_INTEGRITY;
  const bonus = history.completedOaths * COMPLETION_BONUS;
  const fraudCost = history.fraudStrikes * FRAUD_PENALTY;
  const strikeCost = history.failedOaths * STRIKE_PENALTY;
  const decay = history.monthsInactive * 1; // 1 point decay per month

  const score = base + bonus - fraudCost - strikeCost - decay;
  
  // Floor at 0, ceiling is theoretically infinite but realistically ~10k+
  return Math.max(0, score);
}

/**
 * Determines what financial tiers a user can access based on their Integrity Score.
 */
export function getAllowedTiers(score: number): string[] {
  if (score < 20) return ['RESTRICTED_MODE']; // Essentially Shadowbanned
  if (score < 50) return ['TIER_1_MICRO_STAKES']; // Under $20
  if (score < 100) return ['TIER_1_MICRO_STAKES', 'TIER_2_STANDARD']; // Up to $100
  if (score < 500) return ['TIER_1_MICRO_STAKES', 'TIER_2_STANDARD', 'TIER_3_HIGH_ROLLER']; // Up to $1000
  return ['TIER_1_MICRO_STAKES', 'TIER_2_STANDARD', 'TIER_3_HIGH_ROLLER', 'TIER_4_WHALE_VAULTS']; // Unlimited
}

/**
 * RD-01: Fury Accuracy Calculation
 * Evaluates how trustworthy a peer reviewer is.
 */
export const FALSE_ACCUSATION_WEIGHT = 3;

export function calculateAccuracy(history: FuryHistory): number {
  if (history.totalAudits === 0) return 1.0; // Benefit of doubt for new Furies

  // Weighted calculation mathematically punishing false claims 3x
  const netSuccess = history.successfulAudits - (history.falseAccusations * FALSE_ACCUSATION_WEIGHT);
  const ratio = netSuccess / history.totalAudits;

  // Clamp between 0.0 and 1.0
  return Math.max(0.0, Math.min(1.0, ratio));
}

export function shouldDemoteFury(history: FuryHistory): boolean {
  // Triggers demotion if accuracy falls below 80% after a 10 case burn-in period.
  if (history.totalAudits < 10) return false;
  return calculateAccuracy(history) < 0.8;
}

/**
 * Returns the maximum stake amount for a given set of allowed tiers.
 */
/** Returns the maximum stake amount in cents for a given set of allowed tiers. */
export function getTierMaxStake(tiers: string[]): number {
  if (tiers.includes('TIER_4_WHALE_VAULTS')) return Infinity;
  if (tiers.includes('TIER_3_HIGH_ROLLER')) return 100000; // $1,000
  if (tiers.includes('TIER_2_STANDARD')) return 10000; // $100
  if (tiers.includes('TIER_1_MICRO_STAKES')) return 2000; // $20
  return 0;
}


=== MONEY UTILITIES ===
File: src/shared/libs/money.ts

/**
 * Money utilities — all internal amounts are stored as integer cents.
 * Use toCents() at system boundaries (user input) and toDollars() for display.
 */

/** Convert a dollar amount to integer cents. Throws if the result is not an integer. */
export function toCents(dollars: number): number {
  const cents = Math.round(dollars * 100);
  return cents;
}

/** Convert integer cents to a dollar amount for display. */
export function toDollars(cents: number): number {
  return cents / 100;
}

/** Format cents as a dollar string (e.g., 4999 → "$49.99"). */
export function formatCents(cents: number): string {
  return \`$\${(cents / 100).toFixed(2)}\`;
}


=== DATABASE SCHEMA ===
File: src/api/database/schema.sql

-- ARC-07: Double-Entry Ledger Schema
-- Enforce absolute financial integrity for user stakes and bounties.

CREATE TYPE account_type AS ENUM ('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE');

CREATE TABLE accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    type account_type NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    debit_account_id UUID REFERENCES accounts(id) ON DELETE RESTRICT,
    credit_account_id UUID REFERENCES accounts(id) ON DELETE RESTRICT,
    amount DECIMAL(19, 4) NOT NULL CHECK (amount > 0),
    contract_id UUID,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE event_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type TEXT NOT NULL,
    payload JSONB NOT NULL,
    previous_hash TEXT NOT NULL,
    current_hash TEXT NOT NULL, -- hash(previous_hash || payload || created_at)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for rapid sequential verification of the chain.
CREATE INDEX idx_event_log_created_at ON event_log(created_at);

-- Immutability: prevent UPDATE/DELETE on event_log (append-only audit trail)
CREATE OR REPLACE FUNCTION prevent_event_log_mutation()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'event_log is immutable: UPDATE and DELETE are prohibited';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_event_log_immutable
  BEFORE UPDATE OR DELETE ON event_log
  FOR EACH ROW EXECUTE FUNCTION prevent_event_log_mutation();

-- ============================================================
-- Domain Tables: Users, Contracts, Proofs, Fury Assignments
-- ============================================================

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT,
    stripe_customer_id TEXT,
    integrity_score INTEGER DEFAULT 50,
    account_id UUID REFERENCES accounts(id),
    role TEXT DEFAULT 'USER',
    enterprise_id UUID,
    status TEXT DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE contracts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id),
    oath_category TEXT NOT NULL,
    verification_method TEXT NOT NULL,
    stake_amount DECIMAL(19,4) NOT NULL CHECK (stake_amount > 0),
    payment_intent_id TEXT,
    duration_days INTEGER NOT NULL,
    status TEXT DEFAULT 'PENDING_STAKE',
    grace_days_used INTEGER DEFAULT 0,
    strikes INTEGER DEFAULT 0,
    started_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Deferred FK: entries.contract_id references contracts (entries table defined before contracts)
ALTER TABLE entries ADD CONSTRAINT fk_entries_contract_id
  FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE RESTRICT;

-- Auto-update updated_at on row modification
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER contracts_updated_at
    BEFORE UPDATE ON contracts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- Recovery Stream: Accountability Partners & Daily Attestations
-- ============================================================

ALTER TABLE contracts ADD COLUMN metadata JSONB DEFAULT '{}';

CREATE TABLE accountability_partners (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES contracts(id) ON DELETE CASCADE,
    partner_user_id UUID REFERENCES users(id),
    partner_email TEXT,
    status TEXT DEFAULT 'PENDING',  -- PENDING, ACTIVE, VETOED
    invited_at TIMESTAMPTZ DEFAULT NOW(),
    accepted_at TIMESTAMPTZ
);

CREATE TABLE attestations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES contracts(id),
    user_id UUID REFERENCES users(id),
    attestation_date DATE NOT NULL,
    attested_at TIMESTAMPTZ,
    cosigned_by UUID REFERENCES users(id),
    cosigned_at TIMESTAMPTZ,
    status TEXT DEFAULT 'PENDING',  -- PENDING, ATTESTED, COSIGNED, MISSED
    UNIQUE(contract_id, attestation_date)
);

CREATE INDEX idx_attestations_contract_id ON attestations(contract_id);
CREATE INDEX idx_attestations_status ON attestations(status);
CREATE INDEX idx_accountability_partners_contract_id ON accountability_partners(contract_id);

CREATE TABLE proofs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES contracts(id),
    user_id UUID REFERENCES users(id),
    media_uri TEXT,
    proof_type TEXT DEFAULT 'MEDIA',  -- MEDIA, ATTESTATION
    is_honeypot BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'PENDING_REVIEW',
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE fury_assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    proof_id UUID REFERENCES proofs(id),
    fury_user_id UUID REFERENCES users(id),
    verdict TEXT,
    reviewed_at TIMESTAMPTZ,
    assigned_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id),
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT,
    read BOOLEAN DEFAULT FALSE,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_unread ON notifications(user_id, read) WHERE read = FALSE;

-- Stripe webhook idempotency: track processed event IDs
CREATE TABLE stripe_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id TEXT UNIQUE NOT NULL,
    event_type TEXT NOT NULL,
    processed_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_stripe_events_event_id ON stripe_events(event_id);

CREATE TABLE contract_resolution_side_effects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES contracts(id) ON DELETE CASCADE,
    outcome TEXT NOT NULL,
    effect_type TEXT NOT NULL,
    dedupe_key TEXT NOT NULL UNIQUE,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    locked_at TIMESTAMPTZ,
    next_retry_at TIMESTAMPTZ,
    quarantined_at TIMESTAMPTZ,
    quarantine_reason TEXT,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT chk_contract_resolution_effect_status
      CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'QUARANTINED'))
);

CREATE INDEX idx_contract_resolution_effects_contract
  ON contract_resolution_side_effects(contract_id, created_at);
CREATE INDEX idx_contract_resolution_effects_status
  ON contract_resolution_side_effects(status, created_at);
CREATE INDEX idx_contract_resolution_effects_retry_due
  ON contract_resolution_side_effects(status, next_retry_at)
  WHERE status = 'FAILED';
CREATE INDEX idx_contract_resolution_effects_quarantined
  ON contract_resolution_side_effects(status, quarantined_at)
  WHERE status = 'QUARANTINED';

-- B2B Consumption Billing
CREATE TABLE consumption_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    enterprise_id UUID NOT NULL,
    event_type TEXT NOT NULL,
    units INTEGER NOT NULL DEFAULT 1,
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_consumption_logs_enterprise_period
  ON consumption_logs(enterprise_id, recorded_at);
CREATE INDEX idx_consumption_logs_event_type
  ON consumption_logs(enterprise_id, event_type, recorded_at);

CREATE INDEX idx_contracts_user_id ON contracts(user_id);
CREATE INDEX idx_contracts_status ON contracts(status);
CREATE INDEX idx_proofs_contract_id ON proofs(contract_id);
CREATE INDEX idx_proofs_status ON proofs(status);
CREATE INDEX idx_fury_assignments_proof_id ON fury_assignments(proof_id);
CREATE INDEX idx_fury_assignments_fury_user_id ON fury_assignments(fury_user_id);

-- Ledger performance indexes
-- Refresh tokens for JWT rotation
CREATE TABLE refresh_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_token_hash ON refresh_tokens(token_hash);

-- Account lockout columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;

CREATE INDEX idx_entries_debit_account_id ON entries(debit_account_id);
CREATE INDEX idx_entries_credit_account_id ON entries(credit_account_id);
CREATE INDEX idx_entries_contract_id ON entries(contract_id);
CREATE INDEX idx_users_enterprise_id ON users(enterprise_id);


=== FEATURE BACKLOG (executive summary + P0/P1) ===
File: docs/FEATURE-BACKLOG.md

# Styx Feature Backlog: Documentation → Implementation

**Version**: 1.4.0
**Generated**: 2026-02-28
**Codebase Baseline**: v0.8.0 (1,107 tests, 6 workspaces)
**Source Documents Ingested**: 37 markdown files across research, architecture, legal, planning, and brainstorm categories

---

## Executive Summary

### Status Breakdown

| Status | Count | Description |
|--------|-------|-------------|
| IMPLEMENTED | 23 | Working code with tests |
| PARTIAL | 7 | Code exists but incomplete or conditional |
| STUB | 4 | Files/endpoints exist but placeholder logic |
| NOT_STARTED | 44 | Described in docs, no code |
| **Total** | **78** | |

### P0: Beta Blockers (Must-Build for Phase 1 Private Beta)

| ID | Feature | Status | Blocker Reason |
|----|---------|--------|----------------|
| F-MOBILE-01 | Native iOS Camera Module | STUB | Cannot verify proofs without native capture |
| F-CORE-04 | Real-Money Stripe FBO Settlement | PARTIAL | Test-money only; need FBO routing for beta |
| F-AEGIS-03 | Age Gate (18+ Runtime) | IMPLEMENTED | Legal requirement for financial stakes |
| F-VERIFY-06 | Attestation Daily Flow (No-Contact) | IMPLEMENTED | Primary Phase 1 journey depends on this |
| F-WEB-01 | HttpOnly Cookie Auth Migration | IMPLEMENTED | Security requirement before public beta |
| F-LEGAL-01 | Contest Official Rules Engine | IMPLEMENTED | Every contest needs official rules per law |

### P1: Beta Enhancers (Should-Build for Phase 1)

| ID | Feature | Status |
|----|---------|--------|
| F-VERIFY-02 | HealthKit Native Bridge (iOS) | NOT_STARTED |
| F-UX-01 | Identity-Based Onboarding | NOT_STARTED |
| F-UX-03 | Dynamic Downscale Intervention | PARTIAL |
| F-FURY-03 | Cross-Lobby Auditing | NOT_STARTED |
| F-AEGIS-04 | Recovery Protocol Guardrails | PARTIAL |
| F-MOBILE-03 | Push Notifications | PARTIAL |
| F-SOCIAL-07 | Pod-Based Cohorts (Max 5) | NOT_STARTED | New for March 6 Launch |
| F-SOCIAL-08 | Pod-Level Visibility (Active/Out) | NOT_STARTED | Real-time failure broadcast within pod |
| F-SOCIAL-09 | Anonymous Peer Disclosure (First Name) | NOT_STARTED | Pod-only identity for accountability |
| F-FIN-05 | $39 Entry Model ($9 Fee + $30 Stake) | NOT_STARTED | Standardized MVP pricing |
| F-VERIFY-17 | Binary Daily Check-in (Self-Report) | NOT_STARTED | Initial verification fallback for MVP |
| F-VERIFY-15 | Whoop SCORED State Webhooks | NOT_STARTED | Part of Blockchain of Truth v2 |
| F-VERIFY-16 | HealthKit Metadata WasUserEntered | NOT_STARTED | Part of Blockchain of Truth v2 |

### P2: Post-Beta (Phase 2+)

Features that enhance but don't block: PvP lobbies, spectator markets, Plaid integration, B2B therapist dashboard, prediction markets, maintenance pools, referral system, and more (~30 features).

### P3: Future / Research-Only

Advanced features requiring external dependencies or significant R&D: EVM smart contracts, ZKP privacy layer, DECO oracles, brain-computer interfaces, hardware partnerships (~15 features).

### Critical Path: Phase 1 Private Beta

\`\`\`
[Aegis Protocol] ──→ [Age Gate 18+] ──→ [Contest Rules] ──→ [Real-Money FBO]
        │                                                          │
        ↓                                                          ↓
[Native Camera] ──→ [Attestation Flow] ──→ [HttpOnly Auth] ──→ [TestFlight]
\`\`\`

---

## Part I: Full Feature Catalog by Domain

---

### Domain 1: CORE — Ledger, Escrow, Financial Infrastructure

#### F-CORE-01: Double-Entry Ledger Engine

- **Status**: IMPLEMENTED
- **Phase**: Alpha
- **Priority**: P0 (foundation)

=== IMPLEMENTATION STATUS (claim-to-control matrix) ===
File: docs/planning/planning--implementation-status.md

# Implementation Status (Claim-to-Control Matrix)

This document maps high-level product/security/compliance claims to their current implementation status.

Statuses:
- \`Implemented\`: Runtime control exists and is exercised in code/tests.
- \`Partial\`: Control exists but behavior is incomplete, conditional, or environment-dependent.
- \`Planned\`: Documented policy/intent only; runtime control not yet implemented.
- \`Research\`: External analysis or exploratory content; not product policy.

| Claim | Source | Status | Code Paths | Tests / Evidence | Owner |
|---|---|---|---|---|---|
| Global + endpoint-specific rate limiting (\`@nestjs/throttler\`) | \`README.md\`, \`SECURITY.md\` | Implemented | \`/src/api/src/app.module.ts\`, \`/src/api/src/modules/auth/auth.controller.ts\`, \`/src/api/src/modules/contracts/contracts.controller.ts\`, \`/src/api/src/modules/proofs/proofs.controller.ts\` | Typechecked + API route decorators in source | API |
| JWT secret required in production | \`README.md\`, \`SECURITY.md\` | Implemented | \`/src/api/src/modules/auth/auth.service.ts\`, \`/src/api/src/main.ts\` | \`/src/api/src/modules/auth/auth.service.spec.ts\` (token behavior) | API |
| JWT has no fallback secret | \`SECURITY.md\` (old wording) | Partial | \`/src/api/src/modules/auth/auth.service.ts\` (dev/test fallback remains) | Code inspection | API |
| Geofencing by jurisdiction tier | \`README.md\`, \`SECURITY.md\` | Partial | \`/src/api/services/geofencing.ts\`, \`/src/api/src/common/guards/geofence.guard.ts\`, \`/src/api/src/modules/compliance/compliance-policy.service.ts\` | \`/src/api/src/common/guards/geofence.guard.spec.ts\` | API / Compliance |
| \`TIER_2\` refund-only restrictions on monetary-risk actions | Plan / runtime policy | Implemented (initial scope) | \`/src/api/src/modules/compliance/compliance-policy.service.ts\` | \`/src/api/src/common/guards/geofence.guard.spec.ts\` | API / Compliance |
| \`x-styx-state\` geofence override header is test-only (non-production) | Plan / runtime policy | Implemented | \`/src/api/src/modules/compliance/compliance-policy.service.ts\`, \`/src/api/src/common/guards/geofence.guard.ts\` | \`/src/api/src/common/guards/geofence.guard.spec.ts\` | API / Compliance |
| Missing geolocation headers default fail-open (configurable) | Plan / runtime policy | Implemented | \`/src/api/src/modules/compliance/compliance-policy.service.ts\`, \`.env.example\` | \`/src/api/src/common/guards/geofence.guard.spec.ts\` | API / Compliance |
| KYC / identity verification runtime enforcement | \`docs/legal/legal--aegis-protocol.md\` | Planned | (No runtime enforcement yet; reserved flag \`KYC_ENFORCEMENT_ENABLED\`) | \`.env.example\`, \`/src/api/src/modules/compliance/compliance-policy.service.ts\` capability flag | Compliance / Platform |
| Age 18+ strict enforcement | \`docs/legal/legal--aegis-protocol.md\` | Implemented | \`/src/api/src/modules/auth/auth.service.ts\` (register validation), \`/src/api/database/migrations/008_age_gate_terms_acceptance.sql\`, \`/src/web/app/register/page.tsx\`, \`/src/mobile/screens/RegisterScreen.tsx\` | \`/src/api/src/modules/auth/auth.service.spec.ts\` | Compliance / Product |
| Web auth uses HttpOnly cookie JWTs | \`src/web/README.md\` | Implemented | \`/src/web/contexts/AuthContext.tsx\`, \`/src/web/services/api-client.ts\` | Code inspection; cookies set with httpOnly flag | Web |
| Web auth is client-side JWT today | Current runtime | Implemented | \`/src/web/contexts/AuthContext.tsx\`, \`/src/web/services/api-client.ts\`, \`/src/web/proxy.ts\` | Web typecheck (\`/src/web\`), runtime code path | Web |
| Sentry error monitoring | Operational requirement | Implemented | \`/src/api/src/main.ts\` (Sentry.init), \`/src/web/app/error.tsx\`, \`/src/api/src/common/monitoring/\` | Runtime integration; error boundaries in web | Platform |
| Daily attestation flow (Recovery stream) | \`planning--phase1-private-beta-scope.md\` | Implemented | \`/src/api/src/modules/contracts/contracts.service.ts\` (getAttestationStatus, submitAttestation), \`/src/api/src/modules/contracts/contracts.controller.ts\`, \`/src/web/app/contracts/[id]/attest/page.tsx\`, \`/src/mobile/screens/AttestationScreen.tsx\` | \`/src/api/src/modules/contracts/contracts.service.spec.ts\` | Product |
| Cohort snapshot API (roster, Active/Out, pod breakdown) | \`planning--meeting-notes--2026-02.md\`, \`planning--roadmap.md\` | Implemented | \`/src/api/src/modules/contracts/contracts.controller.ts\` (\`GET /contracts/cohorts/:cohortId/snapshot\`), \`/src/api/src/modules/contracts/contracts.service.ts\` (\`getCohortSnapshot\`) | \`/src/api/src/modules/contracts/contracts.controller.spec.ts\`, \`/src/api/src/modules/contracts/contracts.service.spec.ts\` | API / Product |
| Cohort enrollment guardrails (pod required for POD_BASED, max pod size 5, cohort capacity checks) | \`planning--meeting-notes--2026-02.md\`, \`planning--roadmap--mvp-drive.md\` | Implemented | \`/src/api/src/modules/contracts/dto.ts\` (\`CohortEnrollmentDto\`), \`/src/api/src/modules/contracts/contracts.service.ts\` (\`buildCohortMetadata\`) | \`/src/api/src/modules/contracts/contracts.service.spec.ts\`, \`/src/api/src/modules/contracts/contracts.controller.spec.ts\` | API / Product |
| MVP pricing plan metadata (\`MVP_39\` = \`$39\` total, \`$9\` platform fee, \`$30\` refundable stake) | \`planning--roadmap--mvp-drive.md\`, \`brainstorm--transcript--2026-02-27.md\` | Implemented (metadata + stake enforcement) | \`/src/api/src/modules/contracts/dto.ts\` (\`PricingPlan\`), \`/src/api/src/modules/contracts/contracts.service.ts\` (\`normalizeContractPricing\`) | \`/src/api/src/modules/contracts/contracts.service.spec.ts\`, \`/src/api/src/modules/contracts/contracts.controller.spec.ts\` | API / Product |
| Whoop SCORED ingestion endpoint for recovery contracts | \`planning--roadmap.md\`, \`docs/research/research--smart-contracts-behavioral-wagers-v2.md\` | Implemented (initial API path) | \`/src/api/src/modules/contracts/contracts.controller.ts\` (\`POST /contracts/:id/whoop/scored\`), \`/src/api/src/modules/contracts/contracts.service.ts\` (\`submitWhoopScoredState\`) | \`/src/api/src/modules/contracts/contracts.service.spec.ts\`, \`/src/api/src/modules/contracts/contracts.controller.spec.ts\` | API |
| HealthKit manual-entry filter utility (\`HKMetadataKeyWasUserEntered\`) | \`docs/research/research--app-verification-tech-privacy-law.md\`, \`docs/planning/planning--roadmap.md\` | Implemented (guard utility, bridge integration still pending) | \`/src/mobile/services/HealthKitMetadataGuard.ts\` | \`/src/mobile/services/HealthKitMetadataGuard.spec.ts\` | Mobile |
| Contest official rules published | \`docs/legal/legal--compliance-guardrails.md\` §4.C | Implemented | \`/src/web/app/legal/rules/page.tsx\` | Web build; route \`/legal/rules\` | Legal |
| Responsible use disclosures published | \`docs/legal/legal--compliance-guardrails.md\` §4.E | Implemented | \`/src/web/app/legal/responsible-use/page.tsx\` | Web build; route \`/legal/responsible-use\`; links to NCPG, SAMHSA, NEDA, NDVH | Legal |
| Site-wide footer with legal page links | UX / compliance discoverability | Implemented | \`/src/web/components/SiteFooter.tsx\`, \`/src/web/app/layout.tsx\` | Web build; all 4 legal routes linked in footer | Web |
| Legal pages cross-linked ("Related Policies") | UX / compliance discoverability | Implemented | \`/src/web/app/legal/terms/page.tsx\`, \`/src/web/app/legal/privacy/page.tsx\`, \`/src/web/app/legal/rules/page.tsx\`, \`/src/web/app/legal/responsible-use/page.tsx\` | Web build; each page links to the other 3 | Web / Legal |
| Push notifications (local scheduling) | \`research--behavioral-engineering-masters.md\` | Partial | \`/src/mobile/services/NotificationService.ts\` (expo-notifications), \`/src/mobile/services/ApiClient.ts\` (registerPushToken) | \`/src/mobile/services/NotificationService.spec.ts\`; graceful degradation when package unavailable | Mobile |
| Mobile deep linking (styx:// URL scheme) | UX / push notification routing | Implemented | \`/src/mobile/config/linking.ts\` (LinkingOptions + resolveNotificationDeepLink), \`/src/mobile/App.tsx\` (NavigationContainer linking prop + notification tap handler) | \`/src/mobile/config/linking.spec.ts\` (18 tests) | Mobile |
| Endpoint smoke tests (staging + beta) | Operational / CI | Implemented | \`/scripts/smoke/check-endpoints.sh\`, \`/scripts/smoke/staging-smoke.sh\`, \`/scripts/smoke/beta-smoke.sh\` | Script validates health, auth guards, public routes, rate limiting, legal pages | Platform |
| Unified beta readiness contract + artifact (\`beta-readiness-summary.json\`) | Phase 1 release operations | Implemented | \`/scripts/smoke/beta-readiness.sh\`, \`/docs/planning/planning--beta-readiness-contract.md\`, \`/.github/workflows/ci.yml\` | \`npm run beta:readiness\` emits \`artifacts/beta-readiness-summary.json\`; CI uploads artifact in \`beta_readiness\` job | Platform |
| B2B consumption billing (real DB queries) | \`architecture--feasibility-stack.md\` | Implemented | \`/src/api/services/b2b/billing.service.ts\` (consumption_logs table), \`/src/api/database/schema.sql\` | \`/src/api/services/b2b/billing.service.spec.ts\` | API / B2B |
| CRM service (Salesforce/HubSpot connectors) | B2B integration | Implemented | \`/src/api/services/b2b/crm.service.ts\` (graceful fallback) | \`/src/api/services/b2b/crm.service.spec.ts\` | API / B2B |
| Desktop component test coverage | Quality / CI | Implemented | \`/src/desktop/src/components/LedgerInspector.spec.tsx\`, \`/src/desktop/src/components/MacroReview.spec.tsx\` (+ 5 more) | 128 tests across LedgerInspector, MacroReview, ExilePanel, B2BOrchestration, HashCollider, NetworkGuard, LoginScreen | Desktop |
| Web page + component test coverage | Quality / CI | Implemented | \`/src/web/app/dashboard/page.test.tsx\`, \`/src/web/components/SiteFooter.test.tsx\` (+ 25 more) | 166 tests across 27 suites (all pages + key components) | Web |
| Notifications controller spec | Quality / CI | Implemented | \`/src/api/src/modules/notifications/notifications.controller.spec.ts\` | Controller-level test coverage for notifications module | API |
| Legal compliance guardrails long-form memo is product policy | \`docs/legal/legal--compliance-guardrails.md\` (old presentation) | Research | \`/docs/legal/legal--compliance-guardrails.md\` | Labeled as research memo | Compliance |

## Notes

- Use \`/src/api/src/modules/compliance/compliance-policy.service.ts\` as the canonical place for request-level jurisdiction policy decisions.
- Update this matrix in the same PR whenever \`README.md\`, \`SECURITY.md\`, or legal policy docs change claim wording.
- When KYC/age verification is implemented, upgrade the corresponding rows from \`Planned\` to \`Implemented\` only after tests and rollout controls are merged.


=== PHASE 1 PRIVATE BETA SCOPE ===
File: docs/planning/planning--phase1-private-beta-scope.md

# Phase 1 Private Beta Scope (Mobile-First iOS)

This document is the scope lock for the first ship-ready private beta.

## Phase 1 Contract

- **Primary user surface**: iOS mobile app (TestFlight external beta)
- **Primary journey**: No-Contact recovery contracts
- **Money mode**: Test-money pilot (realistic hosted infra, no real-money settlement)
- **Region**: US allowlist only
- **Web role**: Admin/support companion (internal/operator workflows)
- **Desktop role**: Internal judge tool only
- **B2B/HR features**: Internal demo only (not tester-facing)

## Required Product Cuts

- Non-recovery contract categories may exist in code but are hidden or deprioritized in Phase 1 UX.
- Broad consumer web parity is explicitly deferred to Phase 2.
- Android formal beta distribution is deferred to Phase 2 unless iOS/TestFlight is blocked.
- KYC / age runtime enforcement remains out of scope for Phase 1 and must be clearly labeled as not active.

## Beta Labels (User-Facing)

All tester-facing surfaces should clearly communicate:

- \`Private Beta\`
- \`Test-Money Pilot\`
- \`US Allowlist\`

## Internal-Only Surfaces

The following are operator/internal-only in Phase 1:

- Web admin/support operations
- Desktop judge/dispute workflows
- B2B/HR demo flows

## Change Control

Any PR that expands tester-facing scope beyond this document must:

- update this file,
- update \`docs/planning/planning--implementation-status.md\` if claims change,
- update \`docs/planning/planning--beta-readiness-contract.md\` if release gates or readiness policy change,
- include an explicit rationale for the scope change.

## Readiness Source of Truth

Phase 1 release go/no-go is defined by \`docs/planning/planning--beta-readiness-contract.md\`.

- Operational checks must run via \`npm run beta:readiness\`.
- The generated artifact at \`artifacts/beta-readiness-summary.json\` is the canonical evidence format.


=== PROJECT METADATA (seed.yaml) ===
File: seed.yaml

# seed.yaml — Automation Contract for organvm-iii-ergon/peer-audited--behavioral-blockchain
# Schema: seed/v1.0
# Generated: 2026-02-22

schema_version: "1.0"
organ: III
organ_name: Commerce
repo: peer-audited--behavioral-blockchain
org: organvm-iii-ergon

metadata:
  implementation_status: ACTIVE
  tier: standard
  promotion_status: PUBLIC_PROCESS
  last_validated: "2026-02-23"
  generated: "2026-02-22"
  language: typescript
  tags: [nestjs, nextjs, react-native, tauri, stripe, groq, llama, postgresql, redis]

agents:
  - name: ci
    trigger: on_push
    workflow: .github/workflows/ci.yml
    description: "Continuous integration pipeline"

produces:
  - type: product
    description: "Styx: peer-audited behavioral market platform (NestJS API, Next.js web, React Native mobile, Tauri desktop)"

  - type: community_signal
    description: "Product milestones and releases generate community events"
    consumers: [organvm-vi-koinonia/community-hub]
  - type: distribution_signal
    description: "Product updates trigger POSSE distribution via kerygma profile"
    consumers: [organvm-vii-kerygma/social-automation]
consumes:
  - type: governance-rules
    source: ORGAN-IV
    description: Commerce operations follow governance policies

subscriptions:
  - event: governance.updated
    source: ORGAN-IV
    action: Check compliance with updated governance rules
  - event: health-audit.completed
    source: ORGAN-IV
    action: Review audit findings for this repo
  - event: community.event_created
    source: ORGAN-VI
    action: Community event registered for this product
  - event: distribution.dispatched
    source: ORGAN-VII
    action: Announcement distributed via POSSE pipeline
`;
