/**
 * Markdown writer for a ContentPlan.
 *
 * Outputs a markdown file in the same shape as
 * docs/planning/planning--jessica-30-day-content-calendar--2026-06-01.md
 * and its sibling instantiations. The output is human-readable and can be
 * diffed in pull requests.
 */

import type { ContentPlan } from "../types/index.js";

/** Render a ContentPlan as Markdown. */
export function renderMarkdown(plan: ContentPlan): string {
  const lines: string[] = [];

  lines.push(
    `# ${plan.systemName} — 30-Day Content Calendar (Engine-Generated)`,
  );
  lines.push("");
  lines.push(
    `Generated by \`@styx/audience-engine\` from the InstanceConfig. ` +
      `This calendar honors the engine's ratios, cadence, and dual-channel ` +
      `structure. Window: ${plan.startDate} → ${plan.endDate}.`,
  );
  lines.push("");
  lines.push(
    "`H` = Host channel · `P` = Product channel · `O` = owned (email/digest/RSS).",
  );
  lines.push("");

  // Pillars
  lines.push("## Pillars");
  lines.push("");
  lines.push("| # | Pillar | Channel | Ratio | Goal |");
  lines.push("|---|--------|---------|-------|------|");
  for (const p of plan.pillars) {
    lines.push(
      `| ${p.index} | ${p.name} | ${p.channel} | ${p.ratio}% | ${p.goal} |`,
    );
  }
  lines.push("");

  // Weeks
  for (const week of plan.weeks) {
    lines.push(`## ${week.theme}`);
    lines.push("");
    lines.push("| Day | Date | Ch | Format | Hook | Pillar | CTA |");
    lines.push("|-----|------|----|--------|------|--------|-----|");
    for (const day of week.days) {
      const ch = day.channel === "host" ? "H" : "P";
      const cta = day.cta ?? "—";
      lines.push(
        `| ${day.dayOfWeek} | ${day.date} | ${ch} | ${day.format} | ${day.hook} | ${day.pillar} | ${cta} |`,
      );
    }
    lines.push("");
  }

  // Production notes
  lines.push("## Production notes");
  lines.push("");
  lines.push(
    "- This calendar is **engine-generated** and must be reviewed by a human " +
      "before publish. The generator's job is to honor the ratios and cadence; " +
      "the human's job is to add the actual copy.",
  );
  lines.push(
    "- To regenerate: `audience-engine plan --config <yaml> --output <md>`.",
  );
  lines.push("- To customize, edit the InstanceConfig YAML, not this file.");
  lines.push("");
  lines.push("## Linked");
  lines.push("- Engine: `docs/playbooks/playbook--audience-growth-engine.md`");
  lines.push(
    "- Source worksheet: `docs/playbooks/templates/template--instantiation-worksheet.md`",
  );

  return lines.join("\n");
}
